using GameFramework;
using UnityEngine;
using UnityGameFramework.Runtime;

/// <summary>
/// Generic UI helpers built on GF_X data-table configuration.
/// UIViews is generated by the UI tooling for each project.
/// </summary>
public static class UIExtension
{
    public static int OpenUIForm(this UIComponent uiComponent, UIViews viewId, UIParams parameters = null)
    {
        if (GF.DataTable == null || !GF.DataTable.HasDataTable<UITable>() || !GF.DataTable.HasDataTable<UIGroupTable>())
        {
            Log.Warning("UI tables are not loaded. Configure UITable and UIGroupTable before opening UI forms.");
            return -1;
        }

        UITable view = GF.DataTable.GetDataTable<UITable>().GetDataRow((int)viewId);
        if (view == null)
        {
            Log.Warning("No UI configuration exists for view id '{0}'.", (int)viewId);
            return -1;
        }

        UIGroupTable group = GF.DataTable.GetDataTable<UIGroupTable>().GetDataRow(view.UIGroupId);
        if (group == null)
        {
            Log.Warning("No UI group configuration exists for group id '{0}'.", view.UIGroupId);
            return -1;
        }

        parameters ??= UIParams.Create();
        parameters.AllowEscapeClose ??= view.EscapeClose;
        parameters.SortOrder ??= view.SortOrder + group.Depth;
        return uiComponent.OpenUIForm(UtilityBuiltin.AssetsPath.GetUIFormPath(view.UIPrefab), group.Name, view.PauseCoveredUI, parameters);
    }

    public static string GetUIFormAssetName(this UIComponent uiComponent, UIViews viewId)
    {
        if (GF.DataTable == null || !GF.DataTable.HasDataTable<UITable>()) return string.Empty;
        UITable view = GF.DataTable.GetDataTable<UITable>().GetDataRow((int)viewId);
        return view == null ? string.Empty : UtilityBuiltin.AssetsPath.GetUIFormPath(view.UIPrefab);
    }

    public static bool HasUIForm(this UIComponent uiComponent, UIViews viewId)
    {
        string assetName = uiComponent.GetUIFormAssetName(viewId);
        return !string.IsNullOrEmpty(assetName) && uiComponent.HasUIForm(assetName);
    }

    public static int GetTopUIFormId(this UIComponent uiComponent)
    {
        int topId = -1;
        int topOrder = int.MinValue;
        foreach (UIForm form in uiComponent.GetAllLoadedUIForms())
        {
            if (form.Logic is UIFormBase logic && !logic.Params.IsSubUIForm && logic.SortOrder >= topOrder)
            {
                topOrder = logic.SortOrder;
                topId = form.SerialId;
            }
        }
        return topId;
    }

    public static void Close(this UIComponent uiComponent, int serialId)
    {
        if (uiComponent.IsLoadingUIForm(serialId) || !uiComponent.HasUIForm(serialId)) return;
        if (uiComponent.GetUIForm(serialId).Logic is UIFormBase logic) logic.CloseWithAnimation();
        else uiComponent.CloseUIForm(serialId);
    }
}
