#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Unity Skills Python Helper
# Auto-generated by UnitySkills

# CRITICAL: Fix Windows console encoding BEFORE any other imports or print statements
# This must be at the very top of the module to work correctly
import sys
if sys.platform == 'win32':
    import codecs
    if hasattr(sys.stdout, 'buffer'):
        sys.stdout = codecs.getwriter('utf-8')(sys.stdout.buffer, 'replace')
    if hasattr(sys.stderr, 'buffer'):
        sys.stderr = codecs.getwriter('utf-8')(sys.stderr.buffer, 'replace')

    # 14-mcp-encoding-fix: 通过 GetCommandLineW + CommandLineToArgvW 重写 sys.argv，
    # 绕开 Python 默认的 ANSI(cp936) → Unicode 转换层，保证 CJK 参数完整。
    # 现代 Python (3.6+) wmain 已经默认走 Unicode argv，本块在那之上 belt-and-suspenders；
    # MSYS / Cygwin / WSL Python 的 ctypes.windll 不可用，try/except 兜底跳过。
    #
    # CommandLineToArgvW 返回 [exe_path, *python_flags, script, *script_args]，
    # Python 自己的 sys.argv = [script, *script_args]，所以按尾部对齐覆盖。
    try:
        import ctypes
        from ctypes import wintypes
        _get_cmd_line_w = ctypes.windll.kernel32.GetCommandLineW
        _get_cmd_line_w.restype = wintypes.LPCWSTR
        _cmd_to_argv_w = ctypes.windll.shell32.CommandLineToArgvW
        _cmd_to_argv_w.argtypes = [wintypes.LPCWSTR, ctypes.POINTER(ctypes.c_int)]
        _cmd_to_argv_w.restype = ctypes.POINTER(wintypes.LPWSTR)
        _argc = ctypes.c_int(0)
        _argv_w = _cmd_to_argv_w(_get_cmd_line_w(), ctypes.byref(_argc))
        if _argv_w and _argc.value >= len(sys.argv):
            _full = [_argv_w[i] for i in range(_argc.value)]
            sys.argv = _full[-len(sys.argv):]
    except (OSError, AttributeError):
        # MSYS / Cygwin / WSL Python：windll 不可用，保持原 sys.argv
        pass

import requests
import time
import json
import os
from typing import Any, Dict, Optional, Tuple

# legacy 常量：外部脚本可能 import UNITY_URL；内部逻辑一律走 _default_client.url，不再引用此常量
UNITY_URL = "http://localhost:8090"
DEFAULT_PORT = 8090

def get_registry_path():
    return os.path.join(os.path.expanduser("~"), ".unity_skills", "registry.json")

def _load_registry() -> Dict[str, Any]:
    reg_path = get_registry_path()
    if not os.path.exists(reg_path):
        return {}
    try:
        with open(reg_path, 'r', encoding='utf-8') as f:
            return json.load(f)
    except (OSError, json.JSONDecodeError):
        return {}

def _find_port_by_cwd() -> Optional[Tuple[int, str]]:
    """按 cwd 反查 registry；命中返回 (port, "cwd-match(<name>)")，未命中返 None。

    判定「cwd 是项目根本身或子目录」，用 os.path.commonpath 严格判断，
    避免 D:\\proj 误匹配 D:\\proj_backup。Windows 大小写不敏感用 normcase 归一。
    """
    registry = _load_registry()
    if not registry:
        return None
    cwd = os.path.normcase(os.path.normpath(os.getcwd()))
    for path_key, entry in registry.items():
        proj_path = os.path.normcase(os.path.normpath(path_key))
        try:
            if os.path.commonpath([cwd, proj_path]) == proj_path:
                port = entry.get('port')
                name = entry.get('name', path_key)
                if port:
                    return port, f"cwd-match({name})"
        except ValueError:
            continue  # 不同盘符（Windows）
    return None

class UnitySkills:
    """
    Client for interacting with a specific Unity Editor instance.
    """
    def __init__(self, port: int = None, target: str = None, url: str = None):
        """
        Initialize client.
        Args:
            port: Connect to specific localhost port (e.g. 8091)
            target: Connect to instance by Name or ID (e.g. "MyGame" or "MyGame_A1B2") - auto-discovers port.
            url: Full URL override.
        """
        self.url = url

        if not self.url:
            if port:
                self.url = f"http://localhost:{port}"
            elif target:
                found_port = self._find_port_by_target(target)
                if found_port:
                    self.url = f"http://localhost:{found_port}"
                else:
                    raise ValueError(f"Could not find Unity instance matching '{target}' in registry.")
            else:
                self.url = f"http://localhost:{DEFAULT_PORT}"

    def _find_port_by_target(self, target: str) -> Optional[int]:
        data = _load_registry()
        # target 可以是 ID 或 Name
        # 1. Exact ID match
        for path, info in data.items():
            if info.get('id') == target:
                return info.get('port')
        # 2. Exact Name match（同名多项目取首个）
        for path, info in data.items():
            if info.get('name') == target:
                return info.get('port')
        return None

    def call(self, skill_name: str, verbose: bool = False, **kwargs) -> Dict[str, Any]:
        """
        Call a skill on this instance.

        Returns a normalized response with 'success' field and flattened result data.
        """
        try:
            # Combine verbose into kwargs for JSON body
            kwargs['verbose'] = verbose
            # 使用 ensure_ascii=False 保留原始中文字符，避免转义为 \uXXXX
            json_data = json.dumps(kwargs, ensure_ascii=False)
            response = requests.post(
                f"{self.url}/skill/{skill_name}",
                data=json_data.encode('utf-8'),
                headers={'Content-Type': 'application/json; charset=utf-8'},
                timeout=30
            )
            response.encoding = 'utf-8'  # 确保正确解码UTF-8

            try:
                data = response.json()
            except ValueError:
                return {'success': False, 'error': f"Invalid JSON response: {response.text}"}

            # 规范化响应格式：将 {"status": "success", "result": {...}} 转换为 {"success": True, ...}
            if data.get('status') == 'success':
                result = data.get('result', {})
                # 将result的内容提升到顶层，并添加success标志
                normalized = {'success': True}
                if isinstance(result, dict):
                    normalized.update(result)
                else:
                    normalized['result'] = result
                return normalized
            elif data.get('status') == 'error':
                return {
                    'success': False,
                    'error': data.get('error', 'Unknown error'),
                    'message': data.get('message', '')
                }
            else:
                return data

        except requests.exceptions.ConnectionError:
             return {
                'success': False,
                'error': f"Cannot connect to {self.url}. Unity instance may be down.",
                'suggestion': 'Unity may be recompiling scripts (Domain Reload). Wait 3-5 seconds and retry.',
                'hint': 'Check if server is running: Window > UnitySkills > Start Server'
            }
        except Exception as e:
            return {'success': False, 'error': str(e)}

    # --- Proxies for common skills ---
    def create_cube(self, x=0, y=0, z=0, name="Cube"): return self.call("create_cube", x=x, y=y, z=z, name=name)
    def create_sphere(self, x=0, y=0, z=0, name="Sphere"): return self.call("create_sphere", x=x, y=y, z=z, name=name)
    def delete_object(self, name): return self.call("delete_object", objectName=name)


# Global Default Client + 寻址来源（供 health() 排障输出）
_default_client_source: str = ""
_pending_default_warning: str = ""  # 延迟到 pre_parse 之后 / 首次入口调用再 flush，避免 --target 场景误打

def _flush_pending_warning():
    """把 build 阶段积攒的 default warning 一次性 flush 到 stderr。CLI --target/--port 覆盖后调用则本函数无副作用（pending 已被清空）。"""
    global _pending_default_warning
    if _pending_default_warning:
        sys.stderr.write(_pending_default_warning)
        _pending_default_warning = ""

def _build_default_client() -> UnitySkills:
    """按 env > cwd > 8090 优先级构造默认 client；写入 _default_client_source 记录来源。default 兜底的 warning 缓存到 _pending_default_warning，由入口点 flush。"""
    global _default_client_source, _pending_default_warning
    env_target = os.environ.get('UNITY_SKILLS_TARGET')
    if env_target:
        try:
            client = UnitySkills(target=env_target)
            _default_client_source = f"env({env_target})"
            return client
        except ValueError as e:
            sys.stderr.write(
                f"[unity-skills] UNITY_SKILLS_TARGET='{env_target}' 匹配失败: {e}，回退 cwd 匹配\n"
            )
    cwd_hit = _find_port_by_cwd()
    if cwd_hit:
        port, source = cwd_hit
        _default_client_source = source
        return UnitySkills(port=port)
    _pending_default_warning = (
        f"[unity-skills] cwd 未在 registry 匹配到 Unity 项目，回退 DEFAULT_PORT={DEFAULT_PORT}。"
        f"多项目并存请设 UNITY_SKILLS_TARGET 或用 --target=<name>\n"
    )
    _default_client_source = "default"
    return UnitySkills()

_default_client = _build_default_client()

# Auto-workflow configuration
_auto_workflow_enabled = True  # Enable auto-workflow
_current_workflow_active = False  # Is a workflow currently active?

# Skills that should trigger auto-workflow (modification operations)
_workflow_tracked_skills = {
    'gameobject_create', 'gameobject_delete', 'gameobject_rename',
    'gameobject_set_transform', 'gameobject_duplicate', 'gameobject_set_parent',
    'gameobject_set_active', 'gameobject_create_batch', 'gameobject_delete_batch',
    'gameobject_rename_batch', 'gameobject_set_transform_batch',
    'component_add', 'component_remove', 'component_set_property',
    'component_add_batch', 'component_remove_batch', 'component_set_property_batch',
    'material_create', 'material_assign', 'material_set_color', 'material_set_texture',
    'material_set_emission', 'material_set_float', 'material_set_shader',
    'material_create_batch', 'material_assign_batch', 'material_set_colors_batch',
    'light_create', 'light_set_properties', 'light_set_enabled',
    'prefab_create', 'prefab_instantiate', 'prefab_apply', 'prefab_unpack',
    'prefab_instantiate_batch',
    'ui_create_canvas', 'ui_create_panel', 'ui_create_button', 'ui_create_text',
    'ui_create_image', 'ui_create_inputfield', 'ui_create_slider', 'ui_create_toggle',
    'ui_create_batch', 'ui_set_text', 'ui_set_anchor', 'ui_set_rect',
    'script_create', 'script_delete', 'script_create_batch',
    'terrain_create', 'terrain_set_height', 'terrain_set_heights_batch', 'terrain_paint_texture',
    'asset_import', 'asset_delete', 'asset_move', 'asset_duplicate',
    'scene_create', 'scene_save',
}

def set_auto_workflow(enabled: bool):
    """Enable or disable auto-workflow recording."""
    global _auto_workflow_enabled
    _auto_workflow_enabled = enabled

def is_auto_workflow_enabled() -> bool:
    """Check if auto-workflow is enabled."""
    return _auto_workflow_enabled

def connect(port: int = None, target: str = None) -> UnitySkills:
    return UnitySkills(port=port, target=target)

def list_instances() -> list:
    """Return list of active Unity instances from registry."""
    reg_path = get_registry_path()
    if not os.path.exists(reg_path):
        return []
    try:
        with open(reg_path, 'r') as f:
            data = json.load(f)
            return list(data.values())
    except:
        return []

def call_skill(skill_name: str, **kwargs) -> Dict[str, Any]:
    """
    Call a Unity skill, supporting auto-workflow recording.

    If auto-workflow is enabled (default), it will automatically:
    1. Start a workflow task before a modification operation
    2. Execute the operation
    3. End the workflow task
    """
    global _current_workflow_active

    _flush_pending_warning()  # 外部 import 场景：首次进入 API 时把 build 阶段的 default fallback warning 打出来

    # Check if we should track this call
    should_track = (
        _auto_workflow_enabled and
        skill_name in _workflow_tracked_skills and
        not _current_workflow_active and
        not skill_name.startswith('workflow_')  # Avoid recursion
    )

    if should_track:
        # Start workflow
        _current_workflow_active = True
        _default_client.call(
            'workflow_task_start',
            tag=skill_name,
            description=f"Auto: {skill_name} - {str(kwargs)[:100]}"
        )

        # Execute actual operation
        result = _default_client.call(skill_name, **kwargs)

        # End workflow
        _default_client.call('workflow_task_end')
        _current_workflow_active = False

        return result
    else:
        return _default_client.call(skill_name, **kwargs)


class WorkflowContext:
    """
    Workflow context manager for batching multiple operations into a single workflow task.

    Usage:
        with WorkflowContext('Create Scene', 'Build player and environment'):
            call_skill('gameobject_create', name='Player')
            call_skill('component_add', name='Player', componentType='Rigidbody')
    """
    def __init__(self, tag: str, description: str = ''):
        self.tag = tag
        self.description = description

    def __enter__(self):
        global _current_workflow_active
        _current_workflow_active = True
        call_skill('workflow_task_start', tag=self.tag, description=self.description)
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        global _current_workflow_active
        call_skill('workflow_task_end')
        _current_workflow_active = False
        return False  # Do not suppress exceptions

def workflow_context(tag: str, description: str = '') -> WorkflowContext:
    """Convenience function to create a WorkflowContext."""
    return WorkflowContext(tag, description)

def call_skill_with_retry(skill_name: str, max_retries: int = 3, retry_delay: float = 2.0, **kwargs) -> Dict[str, Any]:
    """Call a Unity skill with automatic retry logic for Domain Reload scenarios."""
    for attempt in range(max_retries):
        result = call_skill(skill_name, **kwargs)
        # 检查success字段而不是error字段
        if result.get('success') or ('error' not in result or 'Cannot connect' not in result.get('error', '')):
            return result
        if attempt < max_retries - 1:
            time.sleep(retry_delay)
    return result

def get_skills() -> Dict[str, Any]:
    """Get list of all available skills."""
    _flush_pending_warning()
    try:
        response = requests.get(f"{_default_client.url}/skills", timeout=5)
        response.encoding = 'utf-8'
        return response.json()
    except Exception as e:
        return {"status": "error", "error": str(e)}

def health() -> Dict[str, Any]:
    """检查 Unity server 状态 + 报告寻址来源，便于多项目场景排障。"""
    _flush_pending_warning()
    info = {
        'url': _default_client.url,
        'source': _default_client_source,
    }
    try:
        response = requests.get(f"{_default_client.url}/health", timeout=2)
        response.encoding = 'utf-8'
        info['ok'] = response.json().get("status") == "ok"
    except Exception as e:
        info['ok'] = False
        info['error'] = str(e)
    return info

# ============================================================
# Main CLI Entry Point
# ============================================================
def _pre_parse_routing():
    """从 sys.argv 抽取 --target=<x> / --target <x> / --port=<n> / --port <n>，剔除后重建 _default_client。

    优先级：--port > --target。识别到任一即覆盖 env / cwd 匹配结果。
    argv 剔除后，后续 skill_name / --stdin-json / key=value 解析不受影响。
    """
    global _default_client, _default_client_source
    argv = sys.argv[1:]
    cleaned = []
    port_val: Optional[int] = None
    target_val: Optional[str] = None
    i = 0
    while i < len(argv):
        arg = argv[i]
        if arg.startswith('--port='):
            try:
                port_val = int(arg.split('=', 1)[1])
            except ValueError:
                sys.stderr.write(f"[unity-skills] --port 需要整数，得到 '{arg}'，忽略\n")
            i += 1
            continue
        if arg == '--port' and i + 1 < len(argv):
            try:
                port_val = int(argv[i + 1])
            except ValueError:
                sys.stderr.write(f"[unity-skills] --port 需要整数，得到 '{argv[i + 1]}'，忽略\n")
            i += 2
            continue
        if arg.startswith('--target='):
            target_val = arg.split('=', 1)[1]
            i += 1
            continue
        if arg == '--target' and i + 1 < len(argv):
            target_val = argv[i + 1]
            i += 2
            continue
        cleaned.append(arg)
        i += 1
    sys.argv = [sys.argv[0]] + cleaned

    global _pending_default_warning
    if port_val is not None:
        _default_client = UnitySkills(port=port_val)
        _default_client_source = f"cli-port({port_val})"
        _pending_default_warning = ""  # CLI 覆盖成功 → 撤销 build 阶段的 default fallback warning
    elif target_val is not None:
        try:
            _default_client = UnitySkills(target=target_val)
            _default_client_source = f"cli-target({target_val})"
            _pending_default_warning = ""  # 同上
        except ValueError as e:
            sys.stderr.write(
                f"[unity-skills] --target='{target_val}' 匹配失败: {e}，回退默认 client\n"
            )

def main():
    """Command-line interface for Unity Skills."""
    _pre_parse_routing()
    _flush_pending_warning()  # CLI 场景：pre_parse 已决定要不要保留 build 阶段的 warning

    if len(sys.argv) < 2:
        print('用法: python unity_skills.py <skill_name> [--target=<name>] [--port=<num>] [param1=value1] ...')
        print('     python unity_skills.py <skill_name> --stdin-json   # 参数从 stdin 读 JSON（推荐 CJK 场景）')
        print('     python unity_skills.py health                      # 查看当前寻址来源 + 端口连通性')
        print('示例: python unity_skills.py editor_get_selection')
        print('示例: python unity_skills.py gameobject_create name=MyCube primitiveType=Cube')
        print('示例: python unity_skills.py gameobject_create --target=GameDesigner name=Cube')
        print('示例: echo {"name":"T","text":"设置"} | python unity_skills.py ui_set_text --stdin-json')
        sys.exit(1)

    if sys.argv[1] == "--list":
        print(json.dumps(get_skills(), ensure_ascii=False, indent=2))
        return
    elif sys.argv[1] == "--list-instances":
        print(json.dumps(list_instances(), ensure_ascii=False, indent=2))
        return
    elif sys.argv[1] == "health":
        # 本地 health()：报告寻址来源 + 端口连通性；不打到 unity 服务端
        print(json.dumps(health(), ensure_ascii=False, indent=2))
        return

    skill_name = sys.argv[1]

    # 14-mcp-encoding-fix: --stdin-json 模式从 stdin 读 JSON body
    # 唯一保证 100% 编码安全的入口；CJK / emoji 参数必须用此模式
    if '--stdin-json' in sys.argv[2:]:
        try:
            stdin_bytes = sys.stdin.buffer.read()
        except AttributeError:
            # 已被 codecs wrap：用文本读再转 utf-8
            stdin_bytes = sys.stdin.read().encode('utf-8')
        try:
            params = json.loads(stdin_bytes.decode('utf-8'))
        except (UnicodeDecodeError, json.JSONDecodeError) as e:
            print(json.dumps({
                "success": False,
                "error": f"--stdin-json 模式 stdin 解析失败: {e}",
                "hint": "stdin 必须是 UTF-8 编码的 JSON 对象。调用方推荐 subprocess.run(..., input=json.dumps(params).encode('utf-8'))"
            }, ensure_ascii=False, indent=2))
            sys.exit(2)
        if not isinstance(params, dict):
            print(json.dumps({
                "success": False,
                "error": f"--stdin-json 期望 JSON 对象，实际拿到 {type(params).__name__}",
            }, ensure_ascii=False, indent=2))
            sys.exit(2)
        result = call_skill(skill_name, **params)
        print(json.dumps(result, ensure_ascii=False, indent=2))
        return

    # Parse parameters from argv (legacy 模式)
    params = {}
    for arg in sys.argv[2:]:
        if '=' in arg:
            key, value = arg.split('=', 1)
            # Try to parse as number or boolean
            if value.lower() == 'true':
                value = True
            elif value.lower() == 'false':
                value = False
            elif value.replace('.', '', 1).replace('-', '', 1).isdigit():
                try:
                    value = float(value) if '.' in value else int(value)
                except ValueError:
                    pass
            params[key] = value

    # Call the skill
    result = call_skill(skill_name, **params)

    # Pretty print the result
    print(json.dumps(result, ensure_ascii=False, indent=2))

if __name__ == '__main__':
    main()
