using TMPro;
using UnityEngine;
using UnityEngine.UI;

namespace AutoEra.UI
{
    /// <summary>
    /// BaseCommandHubForm 的契约绑定字段（由 tools/ui_contract_to_form_script.py 依据
    /// Docs/Development/UI-PrefabLayouts/BaseCommandHubForm.contract.json 生成，请勿手改）。
    ///
    /// 与 BaseCommandHubForm.cs 构成同一个 partial 类：字段与只读属性集中在这里，业务逻辑写在
    /// BaseCommandHubForm.cs。新增节点引用只需改契约再重新生成，不必手写字段。
    /// </summary>
    public sealed partial class BaseCommandHubForm
    {
        [SerializeField] private RectTransform _pageHost;
        public RectTransform PageHost => _pageHost;
        [SerializeField] private Button _backButton;
        public Button BackButton => _backButton;
        [SerializeField] private Button _closeButton;
        public Button CloseButton => _closeButton;
        [SerializeField] private RectTransform _hubOverviewEconomyContent;
        public RectTransform HubOverviewEconomyContent => _hubOverviewEconomyContent;
        [SerializeField] private TMP_Text _hubOverviewEconomyBody;
        public TMP_Text HubOverviewEconomyBody => _hubOverviewEconomyBody;
        [SerializeField] private GameObject _hubOverviewEconomyTemplate;
        public GameObject HubOverviewEconomyTemplate => _hubOverviewEconomyTemplate;
        [SerializeField] private RectTransform _hubOverviewOperationContent;
        public RectTransform HubOverviewOperationContent => _hubOverviewOperationContent;
        [SerializeField] private TMP_Text _hubOverviewOperationBody;
        public TMP_Text HubOverviewOperationBody => _hubOverviewOperationBody;
        [SerializeField] private GameObject _hubOverviewOperationTemplate;
        public GameObject HubOverviewOperationTemplate => _hubOverviewOperationTemplate;
        [SerializeField] private RectTransform _hubOverviewAttentionContent;
        public RectTransform HubOverviewAttentionContent => _hubOverviewAttentionContent;
        [SerializeField] private TMP_Text _hubOverviewAttentionBody;
        public TMP_Text HubOverviewAttentionBody => _hubOverviewAttentionBody;
        [SerializeField] private GameObject _hubOverviewAttentionTemplate;
        public GameObject HubOverviewAttentionTemplate => _hubOverviewAttentionTemplate;
        [SerializeField] private GameObject _hubOverviewLoadingState;
        public GameObject HubOverviewLoadingState => _hubOverviewLoadingState;
        [SerializeField] private GameObject _hubOverviewEmptyState;
        public GameObject HubOverviewEmptyState => _hubOverviewEmptyState;
        [SerializeField] private GameObject _hubOverviewErrorState;
        public GameObject HubOverviewErrorState => _hubOverviewErrorState;
        [SerializeField] private GameObject _hubOverviewSuccessState;
        public GameObject HubOverviewSuccessState => _hubOverviewSuccessState;
        [SerializeField] private GameObject _hubOverviewDisabledState;
        public GameObject HubOverviewDisabledState => _hubOverviewDisabledState;
        [SerializeField] private RectTransform _hubTasksQueueContent;
        public RectTransform HubTasksQueueContent => _hubTasksQueueContent;
        [SerializeField] private TMP_Text _hubTasksQueueBody;
        public TMP_Text HubTasksQueueBody => _hubTasksQueueBody;
        [SerializeField] private GameObject _hubTasksQueueTemplate;
        public GameObject HubTasksQueueTemplate => _hubTasksQueueTemplate;
        [SerializeField] private RectTransform _hubTasksDetailContent;
        public RectTransform HubTasksDetailContent => _hubTasksDetailContent;
        [SerializeField] private TMP_Text _hubTasksDetailBody;
        public TMP_Text HubTasksDetailBody => _hubTasksDetailBody;
        [SerializeField] private GameObject _hubTasksDetailTemplate;
        public GameObject HubTasksDetailTemplate => _hubTasksDetailTemplate;
        [SerializeField] private GameObject _hubTasksLoadingState;
        public GameObject HubTasksLoadingState => _hubTasksLoadingState;
        [SerializeField] private GameObject _hubTasksEmptyState;
        public GameObject HubTasksEmptyState => _hubTasksEmptyState;
        [SerializeField] private GameObject _hubTasksErrorState;
        public GameObject HubTasksErrorState => _hubTasksErrorState;
        [SerializeField] private GameObject _hubTasksSuccessState;
        public GameObject HubTasksSuccessState => _hubTasksSuccessState;
        [SerializeField] private GameObject _hubTasksDisabledState;
        public GameObject HubTasksDisabledState => _hubTasksDisabledState;
        [SerializeField] private RectTransform _hubObjectsIndexContent;
        public RectTransform HubObjectsIndexContent => _hubObjectsIndexContent;
        [SerializeField] private TMP_Text _hubObjectsIndexBody;
        public TMP_Text HubObjectsIndexBody => _hubObjectsIndexBody;
        [SerializeField] private GameObject _hubObjectsIndexTemplate;
        public GameObject HubObjectsIndexTemplate => _hubObjectsIndexTemplate;
        [SerializeField] private RectTransform _hubObjectsDetailContent;
        public RectTransform HubObjectsDetailContent => _hubObjectsDetailContent;
        [SerializeField] private TMP_Text _hubObjectsDetailBody;
        public TMP_Text HubObjectsDetailBody => _hubObjectsDetailBody;
        [SerializeField] private GameObject _hubObjectsDetailTemplate;
        public GameObject HubObjectsDetailTemplate => _hubObjectsDetailTemplate;
        [SerializeField] private GameObject _hubObjectsLoadingState;
        public GameObject HubObjectsLoadingState => _hubObjectsLoadingState;
        [SerializeField] private GameObject _hubObjectsEmptyState;
        public GameObject HubObjectsEmptyState => _hubObjectsEmptyState;
        [SerializeField] private GameObject _hubObjectsErrorState;
        public GameObject HubObjectsErrorState => _hubObjectsErrorState;
        [SerializeField] private GameObject _hubObjectsSuccessState;
        public GameObject HubObjectsSuccessState => _hubObjectsSuccessState;
        [SerializeField] private GameObject _hubObjectsDisabledState;
        public GameObject HubObjectsDisabledState => _hubObjectsDisabledState;
        [SerializeField] private RectTransform _hubEnergySummaryContent;
        public RectTransform HubEnergySummaryContent => _hubEnergySummaryContent;
        [SerializeField] private TMP_Text _hubEnergySummaryBody;
        public TMP_Text HubEnergySummaryBody => _hubEnergySummaryBody;
        [SerializeField] private GameObject _hubEnergySummaryTemplate;
        public GameObject HubEnergySummaryTemplate => _hubEnergySummaryTemplate;
        [SerializeField] private RectTransform _hubEnergyFacilitiesContent;
        public RectTransform HubEnergyFacilitiesContent => _hubEnergyFacilitiesContent;
        [SerializeField] private TMP_Text _hubEnergyFacilitiesBody;
        public TMP_Text HubEnergyFacilitiesBody => _hubEnergyFacilitiesBody;
        [SerializeField] private GameObject _hubEnergyFacilitiesTemplate;
        public GameObject HubEnergyFacilitiesTemplate => _hubEnergyFacilitiesTemplate;
        [SerializeField] private RectTransform _hubEnergyConsumersContent;
        public RectTransform HubEnergyConsumersContent => _hubEnergyConsumersContent;
        [SerializeField] private TMP_Text _hubEnergyConsumersBody;
        public TMP_Text HubEnergyConsumersBody => _hubEnergyConsumersBody;
        [SerializeField] private GameObject _hubEnergyConsumersTemplate;
        public GameObject HubEnergyConsumersTemplate => _hubEnergyConsumersTemplate;
        [SerializeField] private GameObject _hubEnergyLoadingState;
        public GameObject HubEnergyLoadingState => _hubEnergyLoadingState;
        [SerializeField] private GameObject _hubEnergyEmptyState;
        public GameObject HubEnergyEmptyState => _hubEnergyEmptyState;
        [SerializeField] private GameObject _hubEnergyErrorState;
        public GameObject HubEnergyErrorState => _hubEnergyErrorState;
        [SerializeField] private GameObject _hubEnergySuccessState;
        public GameObject HubEnergySuccessState => _hubEnergySuccessState;
        [SerializeField] private GameObject _hubEnergyDisabledState;
        public GameObject HubEnergyDisabledState => _hubEnergyDisabledState;
        [SerializeField] private RectTransform _hubRulesInstancesContent;
        public RectTransform HubRulesInstancesContent => _hubRulesInstancesContent;
        [SerializeField] private TMP_Text _hubRulesInstancesBody;
        public TMP_Text HubRulesInstancesBody => _hubRulesInstancesBody;
        [SerializeField] private GameObject _hubRulesInstancesTemplate;
        public GameObject HubRulesInstancesTemplate => _hubRulesInstancesTemplate;
        [SerializeField] private RectTransform _hubRulesConfigurationContent;
        public RectTransform HubRulesConfigurationContent => _hubRulesConfigurationContent;
        [SerializeField] private TMP_Text _hubRulesConfigurationBody;
        public TMP_Text HubRulesConfigurationBody => _hubRulesConfigurationBody;
        [SerializeField] private GameObject _hubRulesConfigurationTemplate;
        public GameObject HubRulesConfigurationTemplate => _hubRulesConfigurationTemplate;
        [SerializeField] private RectTransform _hubRulesImpactContent;
        public RectTransform HubRulesImpactContent => _hubRulesImpactContent;
        [SerializeField] private TMP_Text _hubRulesImpactBody;
        public TMP_Text HubRulesImpactBody => _hubRulesImpactBody;
        [SerializeField] private GameObject _hubRulesImpactTemplate;
        public GameObject HubRulesImpactTemplate => _hubRulesImpactTemplate;
        [SerializeField] private GameObject _hubRulesLoadingState;
        public GameObject HubRulesLoadingState => _hubRulesLoadingState;
        [SerializeField] private GameObject _hubRulesEmptyState;
        public GameObject HubRulesEmptyState => _hubRulesEmptyState;
        [SerializeField] private GameObject _hubRulesErrorState;
        public GameObject HubRulesErrorState => _hubRulesErrorState;
        [SerializeField] private GameObject _hubRulesSuccessState;
        public GameObject HubRulesSuccessState => _hubRulesSuccessState;
        [SerializeField] private GameObject _hubRulesDisabledState;
        public GameObject HubRulesDisabledState => _hubRulesDisabledState;
        [SerializeField] private RectTransform _hubStatsMetricsContent;
        public RectTransform HubStatsMetricsContent => _hubStatsMetricsContent;
        [SerializeField] private TMP_Text _hubStatsMetricsBody;
        public TMP_Text HubStatsMetricsBody => _hubStatsMetricsBody;
        [SerializeField] private GameObject _hubStatsMetricsTemplate;
        public GameObject HubStatsMetricsTemplate => _hubStatsMetricsTemplate;
        [SerializeField] private RectTransform _hubStatsValuesContent;
        public RectTransform HubStatsValuesContent => _hubStatsValuesContent;
        [SerializeField] private TMP_Text _hubStatsValuesBody;
        public TMP_Text HubStatsValuesBody => _hubStatsValuesBody;
        [SerializeField] private GameObject _hubStatsValuesTemplate;
        public GameObject HubStatsValuesTemplate => _hubStatsValuesTemplate;
        [SerializeField] private RectTransform _hubStatsRecordsContent;
        public RectTransform HubStatsRecordsContent => _hubStatsRecordsContent;
        [SerializeField] private TMP_Text _hubStatsRecordsBody;
        public TMP_Text HubStatsRecordsBody => _hubStatsRecordsBody;
        [SerializeField] private GameObject _hubStatsRecordsTemplate;
        public GameObject HubStatsRecordsTemplate => _hubStatsRecordsTemplate;
        [SerializeField] private GameObject _hubStatsLoadingState;
        public GameObject HubStatsLoadingState => _hubStatsLoadingState;
        [SerializeField] private GameObject _hubStatsEmptyState;
        public GameObject HubStatsEmptyState => _hubStatsEmptyState;
        [SerializeField] private GameObject _hubStatsErrorState;
        public GameObject HubStatsErrorState => _hubStatsErrorState;
        [SerializeField] private GameObject _hubStatsSuccessState;
        public GameObject HubStatsSuccessState => _hubStatsSuccessState;
        [SerializeField] private GameObject _hubStatsDisabledState;
        public GameObject HubStatsDisabledState => _hubStatsDisabledState;
        [SerializeField] private RectTransform _remoteMachineOverviewContent;
        public RectTransform RemoteMachineOverviewContent => _remoteMachineOverviewContent;
        [SerializeField] private TMP_Text _remoteMachineOverviewBody;
        public TMP_Text RemoteMachineOverviewBody => _remoteMachineOverviewBody;
        [SerializeField] private GameObject _remoteMachineOverviewTemplate;
        public GameObject RemoteMachineOverviewTemplate => _remoteMachineOverviewTemplate;
        [SerializeField] private RectTransform _remoteMachineHardwareContent;
        public RectTransform RemoteMachineHardwareContent => _remoteMachineHardwareContent;
        [SerializeField] private TMP_Text _remoteMachineHardwareBody;
        public TMP_Text RemoteMachineHardwareBody => _remoteMachineHardwareBody;
        [SerializeField] private GameObject _remoteMachineHardwareTemplate;
        public GameObject RemoteMachineHardwareTemplate => _remoteMachineHardwareTemplate;
        [SerializeField] private RectTransform _remoteMachineAlgorithmsContent;
        public RectTransform RemoteMachineAlgorithmsContent => _remoteMachineAlgorithmsContent;
        [SerializeField] private TMP_Text _remoteMachineAlgorithmsBody;
        public TMP_Text RemoteMachineAlgorithmsBody => _remoteMachineAlgorithmsBody;
        [SerializeField] private GameObject _remoteMachineAlgorithmsTemplate;
        public GameObject RemoteMachineAlgorithmsTemplate => _remoteMachineAlgorithmsTemplate;
        [SerializeField] private GameObject _remoteMachineLoadingState;
        public GameObject RemoteMachineLoadingState => _remoteMachineLoadingState;
        [SerializeField] private GameObject _remoteMachineEmptyState;
        public GameObject RemoteMachineEmptyState => _remoteMachineEmptyState;
        [SerializeField] private GameObject _remoteMachineErrorState;
        public GameObject RemoteMachineErrorState => _remoteMachineErrorState;
        [SerializeField] private GameObject _remoteMachineSuccessState;
        public GameObject RemoteMachineSuccessState => _remoteMachineSuccessState;
        [SerializeField] private GameObject _remoteMachineDisabledState;
        public GameObject RemoteMachineDisabledState => _remoteMachineDisabledState;
        [SerializeField] private GameObject[] _pageRoots;
        public GameObject[] PageRoots => _pageRoots;
        [SerializeField] private Button[] _navButtons;
        public Button[] NavButtons => _navButtons;
    }
}
