using TMPro;
using UnityEngine;
using UnityEngine.UI;

namespace AutoEra.UI
{
    /// <summary>
    /// FieldHudForm 的契约绑定字段（由 tools/ui_contract_to_form_script.py 依据
    /// Docs/Development/UI-PrefabLayouts/FieldHudForm.contract.json 生成，请勿手改）。
    ///
    /// 与 FieldHudForm.cs 构成同一个 partial 类：字段与只读属性集中在这里，业务逻辑写在
    /// FieldHudForm.cs。新增节点引用只需改契约再重新生成，不必手写字段。
    /// </summary>
    public sealed partial class FieldHudForm
    {
        [SerializeField] private RectTransform _pageHost;
        public RectTransform PageHost => _pageHost;
        [SerializeField] private GameObject _firstInteractable;
        public GameObject FirstInteractable => _firstInteractable;
        [SerializeField] private Button _fieldCloseButton;
        public Button FieldCloseButton => _fieldCloseButton;
        [SerializeField] private GameObject _statusPanel;
        public GameObject StatusPanel => _statusPanel;
        [SerializeField] private GameObject _trackerPanel;
        public GameObject TrackerPanel => _trackerPanel;
        [SerializeField] private GameObject _alertsPanel;
        public GameObject AlertsPanel => _alertsPanel;
        [SerializeField] private GameObject _navigationPanel;
        public GameObject NavigationPanel => _navigationPanel;
        [SerializeField] private GameObject _savePanel;
        public GameObject SavePanel => _savePanel;
        [SerializeField] private TMP_Text _statusSummary;
        public TMP_Text StatusSummary => _statusSummary;
        [SerializeField] private Button _hudHubButton;
        public Button HudHubButton => _hudHubButton;
        [SerializeField] private Button _hudTasksButton;
        public Button HudTasksButton => _hudTasksButton;
        [SerializeField] private Button _hudMachinesButton;
        public Button HudMachinesButton => _hudMachinesButton;
        [SerializeField] private Button _hudBuildButton;
        public Button HudBuildButton => _hudBuildButton;
        [SerializeField] private Button _hudShopButton;
        public Button HudShopButton => _hudShopButton;
        [SerializeField] private Button _hudComponentsButton;
        public Button HudComponentsButton => _hudComponentsButton;
        [SerializeField] private Button _hudSystemButton;
        public Button HudSystemButton => _hudSystemButton;
        [SerializeField] private Button _machineOverviewDiagnosticButton;
        public Button MachineOverviewDiagnosticButton => _machineOverviewDiagnosticButton;
        [SerializeField] private Button _machineDiagnosticsTaskRecordButton;
        public Button MachineDiagnosticsTaskRecordButton => _machineDiagnosticsTaskRecordButton;
        [SerializeField] private Button _machineDiagnosticsRunRecordButton;
        public Button MachineDiagnosticsRunRecordButton => _machineDiagnosticsRunRecordButton;
        [SerializeField] private Button _farmRecordButton;
        public Button FarmRecordButton => _farmRecordButton;
        [SerializeField] private Button _forestRecordButton;
        public Button ForestRecordButton => _forestRecordButton;
        [SerializeField] private Button _mineralRecordButton;
        public Button MineralRecordButton => _mineralRecordButton;
        [SerializeField] private Button _waterRecordButton;
        public Button WaterRecordButton => _waterRecordButton;
        [SerializeField] private Button _warehouseBuildingRecordsButton;
        public Button WarehouseBuildingRecordsButton => _warehouseBuildingRecordsButton;
        [SerializeField] private Button _machineOverviewAlgorithmButton;
        public Button MachineOverviewAlgorithmButton => _machineOverviewAlgorithmButton;
        [SerializeField] private Button _machineAlgorithmEditButton;
        public Button MachineAlgorithmEditButton => _machineAlgorithmEditButton;
        [SerializeField] private Button _machineAlgorithmTemplateButton;
        public Button MachineAlgorithmTemplateButton => _machineAlgorithmTemplateButton;
        [SerializeField] private Button _farmKnowledgeButton;
        public Button FarmKnowledgeButton => _farmKnowledgeButton;
        [SerializeField] private Button _forestKnowledgeButton;
        public Button ForestKnowledgeButton => _forestKnowledgeButton;
        [SerializeField] private Button _mineralKnowledgeButton;
        public Button MineralKnowledgeButton => _mineralKnowledgeButton;
        [SerializeField] private Button _waterKnowledgeButton;
        public Button WaterKnowledgeButton => _waterKnowledgeButton;
        [SerializeField] private Button _hudAlertsOpenButton;
        public Button HudAlertsOpenButton => _hudAlertsOpenButton;
        [SerializeField] private Button _hudTrackerTaskButton;
        public Button HudTrackerTaskButton => _hudTrackerTaskButton;
        [SerializeField] private Button _machineOverviewFocusButton;
        public Button MachineOverviewFocusButton => _machineOverviewFocusButton;
        [SerializeField] private Button _farmFocusButton;
        public Button FarmFocusButton => _farmFocusButton;
        [SerializeField] private Button _forestFocusButton;
        public Button ForestFocusButton => _forestFocusButton;
        [SerializeField] private Button _mineralFocusButton;
        public Button MineralFocusButton => _mineralFocusButton;
        [SerializeField] private Button _waterFocusButton;
        public Button WaterFocusButton => _waterFocusButton;
        [SerializeField] private Button _buildingOverviewFocusButton;
        public Button BuildingOverviewFocusButton => _buildingOverviewFocusButton;
        [SerializeField] private RectTransform _machineOverviewIdentityContent;
        public RectTransform MachineOverviewIdentityContent => _machineOverviewIdentityContent;
        [SerializeField] private TMP_Text _machineOverviewIdentityBody;
        public TMP_Text MachineOverviewIdentityBody => _machineOverviewIdentityBody;
        [SerializeField] private GameObject _machineOverviewIdentityTemplate;
        public GameObject MachineOverviewIdentityTemplate => _machineOverviewIdentityTemplate;
        [SerializeField] private RectTransform _machineOverviewCapacityContent;
        public RectTransform MachineOverviewCapacityContent => _machineOverviewCapacityContent;
        [SerializeField] private TMP_Text _machineOverviewCapacityBody;
        public TMP_Text MachineOverviewCapacityBody => _machineOverviewCapacityBody;
        [SerializeField] private GameObject _machineOverviewCapacityTemplate;
        public GameObject MachineOverviewCapacityTemplate => _machineOverviewCapacityTemplate;
        [SerializeField] private GameObject _machineOverviewLoadingState;
        public GameObject MachineOverviewLoadingState => _machineOverviewLoadingState;
        [SerializeField] private GameObject _machineOverviewEmptyState;
        public GameObject MachineOverviewEmptyState => _machineOverviewEmptyState;
        [SerializeField] private GameObject _machineOverviewErrorState;
        public GameObject MachineOverviewErrorState => _machineOverviewErrorState;
        [SerializeField] private GameObject _machineOverviewSuccessState;
        public GameObject MachineOverviewSuccessState => _machineOverviewSuccessState;
        [SerializeField] private GameObject _machineOverviewDisabledState;
        public GameObject MachineOverviewDisabledState => _machineOverviewDisabledState;
        [SerializeField] private RectTransform _machineHardwareSlotsContent;
        public RectTransform MachineHardwareSlotsContent => _machineHardwareSlotsContent;
        [SerializeField] private TMP_Text _machineHardwareSlotsBody;
        public TMP_Text MachineHardwareSlotsBody => _machineHardwareSlotsBody;
        [SerializeField] private GameObject _machineHardwareSlotsTemplate;
        public GameObject MachineHardwareSlotsTemplate => _machineHardwareSlotsTemplate;
        [SerializeField] private RectTransform _machineHardwareComponentContent;
        public RectTransform MachineHardwareComponentContent => _machineHardwareComponentContent;
        [SerializeField] private TMP_Text _machineHardwareComponentBody;
        public TMP_Text MachineHardwareComponentBody => _machineHardwareComponentBody;
        [SerializeField] private GameObject _machineHardwareComponentTemplate;
        public GameObject MachineHardwareComponentTemplate => _machineHardwareComponentTemplate;
        [SerializeField] private GameObject _machineHardwareLoadingState;
        public GameObject MachineHardwareLoadingState => _machineHardwareLoadingState;
        [SerializeField] private GameObject _machineHardwareEmptyState;
        public GameObject MachineHardwareEmptyState => _machineHardwareEmptyState;
        [SerializeField] private GameObject _machineHardwareErrorState;
        public GameObject MachineHardwareErrorState => _machineHardwareErrorState;
        [SerializeField] private GameObject _machineHardwareSuccessState;
        public GameObject MachineHardwareSuccessState => _machineHardwareSuccessState;
        [SerializeField] private GameObject _machineHardwareDisabledState;
        public GameObject MachineHardwareDisabledState => _machineHardwareDisabledState;
        [SerializeField] private RectTransform _machineAlgorithmInstancesContent;
        public RectTransform MachineAlgorithmInstancesContent => _machineAlgorithmInstancesContent;
        [SerializeField] private TMP_Text _machineAlgorithmInstancesBody;
        public TMP_Text MachineAlgorithmInstancesBody => _machineAlgorithmInstancesBody;
        [SerializeField] private GameObject _machineAlgorithmInstancesTemplate;
        public GameObject MachineAlgorithmInstancesTemplate => _machineAlgorithmInstancesTemplate;
        [SerializeField] private RectTransform _machineAlgorithmParametersContent;
        public RectTransform MachineAlgorithmParametersContent => _machineAlgorithmParametersContent;
        [SerializeField] private TMP_Text _machineAlgorithmParametersBody;
        public TMP_Text MachineAlgorithmParametersBody => _machineAlgorithmParametersBody;
        [SerializeField] private GameObject _machineAlgorithmParametersTemplate;
        public GameObject MachineAlgorithmParametersTemplate => _machineAlgorithmParametersTemplate;
        [SerializeField] private GameObject _machineAlgorithmLoadingState;
        public GameObject MachineAlgorithmLoadingState => _machineAlgorithmLoadingState;
        [SerializeField] private GameObject _machineAlgorithmEmptyState;
        public GameObject MachineAlgorithmEmptyState => _machineAlgorithmEmptyState;
        [SerializeField] private GameObject _machineAlgorithmErrorState;
        public GameObject MachineAlgorithmErrorState => _machineAlgorithmErrorState;
        [SerializeField] private GameObject _machineAlgorithmSuccessState;
        public GameObject MachineAlgorithmSuccessState => _machineAlgorithmSuccessState;
        [SerializeField] private GameObject _machineAlgorithmDisabledState;
        public GameObject MachineAlgorithmDisabledState => _machineAlgorithmDisabledState;
        [SerializeField] private RectTransform _machineDiagnosticsTasksContent;
        public RectTransform MachineDiagnosticsTasksContent => _machineDiagnosticsTasksContent;
        [SerializeField] private TMP_Text _machineDiagnosticsTasksBody;
        public TMP_Text MachineDiagnosticsTasksBody => _machineDiagnosticsTasksBody;
        [SerializeField] private GameObject _machineDiagnosticsTasksTemplate;
        public GameObject MachineDiagnosticsTasksTemplate => _machineDiagnosticsTasksTemplate;
        [SerializeField] private RectTransform _machineDiagnosticsComputeContent;
        public RectTransform MachineDiagnosticsComputeContent => _machineDiagnosticsComputeContent;
        [SerializeField] private TMP_Text _machineDiagnosticsComputeBody;
        public TMP_Text MachineDiagnosticsComputeBody => _machineDiagnosticsComputeBody;
        [SerializeField] private GameObject _machineDiagnosticsComputeTemplate;
        public GameObject MachineDiagnosticsComputeTemplate => _machineDiagnosticsComputeTemplate;
        [SerializeField] private GameObject _machineDiagnosticsLoadingState;
        public GameObject MachineDiagnosticsLoadingState => _machineDiagnosticsLoadingState;
        [SerializeField] private GameObject _machineDiagnosticsEmptyState;
        public GameObject MachineDiagnosticsEmptyState => _machineDiagnosticsEmptyState;
        [SerializeField] private GameObject _machineDiagnosticsErrorState;
        public GameObject MachineDiagnosticsErrorState => _machineDiagnosticsErrorState;
        [SerializeField] private GameObject _machineDiagnosticsSuccessState;
        public GameObject MachineDiagnosticsSuccessState => _machineDiagnosticsSuccessState;
        [SerializeField] private GameObject _machineDiagnosticsDisabledState;
        public GameObject MachineDiagnosticsDisabledState => _machineDiagnosticsDisabledState;
        [SerializeField] private RectTransform _farmPublicContent;
        public RectTransform FarmPublicContent => _farmPublicContent;
        [SerializeField] private TMP_Text _farmPublicBody;
        public TMP_Text FarmPublicBody => _farmPublicBody;
        [SerializeField] private GameObject _farmPublicTemplate;
        public GameObject FarmPublicTemplate => _farmPublicTemplate;
        [SerializeField] private RectTransform _farmSensorContent;
        public RectTransform FarmSensorContent => _farmSensorContent;
        [SerializeField] private TMP_Text _farmSensorBody;
        public TMP_Text FarmSensorBody => _farmSensorBody;
        [SerializeField] private GameObject _farmSensorTemplate;
        public GameObject FarmSensorTemplate => _farmSensorTemplate;
        [SerializeField] private RectTransform _farmRecordContent;
        public RectTransform FarmRecordContent => _farmRecordContent;
        [SerializeField] private TMP_Text _farmRecordBody;
        public TMP_Text FarmRecordBody => _farmRecordBody;
        [SerializeField] private GameObject _farmRecordTemplate;
        public GameObject FarmRecordTemplate => _farmRecordTemplate;
        [SerializeField] private GameObject _farmLoadingState;
        public GameObject FarmLoadingState => _farmLoadingState;
        [SerializeField] private GameObject _farmEmptyState;
        public GameObject FarmEmptyState => _farmEmptyState;
        [SerializeField] private GameObject _farmErrorState;
        public GameObject FarmErrorState => _farmErrorState;
        [SerializeField] private GameObject _farmSuccessState;
        public GameObject FarmSuccessState => _farmSuccessState;
        [SerializeField] private GameObject _farmDisabledState;
        public GameObject FarmDisabledState => _farmDisabledState;
        [SerializeField] private RectTransform _forestPublicContent;
        public RectTransform ForestPublicContent => _forestPublicContent;
        [SerializeField] private TMP_Text _forestPublicBody;
        public TMP_Text ForestPublicBody => _forestPublicBody;
        [SerializeField] private GameObject _forestPublicTemplate;
        public GameObject ForestPublicTemplate => _forestPublicTemplate;
        [SerializeField] private RectTransform _forestSensorContent;
        public RectTransform ForestSensorContent => _forestSensorContent;
        [SerializeField] private TMP_Text _forestSensorBody;
        public TMP_Text ForestSensorBody => _forestSensorBody;
        [SerializeField] private GameObject _forestSensorTemplate;
        public GameObject ForestSensorTemplate => _forestSensorTemplate;
        [SerializeField] private RectTransform _forestRecordContent;
        public RectTransform ForestRecordContent => _forestRecordContent;
        [SerializeField] private TMP_Text _forestRecordBody;
        public TMP_Text ForestRecordBody => _forestRecordBody;
        [SerializeField] private GameObject _forestRecordTemplate;
        public GameObject ForestRecordTemplate => _forestRecordTemplate;
        [SerializeField] private GameObject _forestLoadingState;
        public GameObject ForestLoadingState => _forestLoadingState;
        [SerializeField] private GameObject _forestEmptyState;
        public GameObject ForestEmptyState => _forestEmptyState;
        [SerializeField] private GameObject _forestErrorState;
        public GameObject ForestErrorState => _forestErrorState;
        [SerializeField] private GameObject _forestSuccessState;
        public GameObject ForestSuccessState => _forestSuccessState;
        [SerializeField] private GameObject _forestDisabledState;
        public GameObject ForestDisabledState => _forestDisabledState;
        [SerializeField] private RectTransform _mineralPublicContent;
        public RectTransform MineralPublicContent => _mineralPublicContent;
        [SerializeField] private TMP_Text _mineralPublicBody;
        public TMP_Text MineralPublicBody => _mineralPublicBody;
        [SerializeField] private GameObject _mineralPublicTemplate;
        public GameObject MineralPublicTemplate => _mineralPublicTemplate;
        [SerializeField] private RectTransform _mineralSensorContent;
        public RectTransform MineralSensorContent => _mineralSensorContent;
        [SerializeField] private TMP_Text _mineralSensorBody;
        public TMP_Text MineralSensorBody => _mineralSensorBody;
        [SerializeField] private GameObject _mineralSensorTemplate;
        public GameObject MineralSensorTemplate => _mineralSensorTemplate;
        [SerializeField] private RectTransform _mineralRecordContent;
        public RectTransform MineralRecordContent => _mineralRecordContent;
        [SerializeField] private TMP_Text _mineralRecordBody;
        public TMP_Text MineralRecordBody => _mineralRecordBody;
        [SerializeField] private GameObject _mineralRecordTemplate;
        public GameObject MineralRecordTemplate => _mineralRecordTemplate;
        [SerializeField] private GameObject _mineralLoadingState;
        public GameObject MineralLoadingState => _mineralLoadingState;
        [SerializeField] private GameObject _mineralEmptyState;
        public GameObject MineralEmptyState => _mineralEmptyState;
        [SerializeField] private GameObject _mineralErrorState;
        public GameObject MineralErrorState => _mineralErrorState;
        [SerializeField] private GameObject _mineralSuccessState;
        public GameObject MineralSuccessState => _mineralSuccessState;
        [SerializeField] private GameObject _mineralDisabledState;
        public GameObject MineralDisabledState => _mineralDisabledState;
        [SerializeField] private RectTransform _waterPublicContent;
        public RectTransform WaterPublicContent => _waterPublicContent;
        [SerializeField] private TMP_Text _waterPublicBody;
        public TMP_Text WaterPublicBody => _waterPublicBody;
        [SerializeField] private GameObject _waterPublicTemplate;
        public GameObject WaterPublicTemplate => _waterPublicTemplate;
        [SerializeField] private RectTransform _waterSensorContent;
        public RectTransform WaterSensorContent => _waterSensorContent;
        [SerializeField] private TMP_Text _waterSensorBody;
        public TMP_Text WaterSensorBody => _waterSensorBody;
        [SerializeField] private GameObject _waterSensorTemplate;
        public GameObject WaterSensorTemplate => _waterSensorTemplate;
        [SerializeField] private RectTransform _waterRecordContent;
        public RectTransform WaterRecordContent => _waterRecordContent;
        [SerializeField] private TMP_Text _waterRecordBody;
        public TMP_Text WaterRecordBody => _waterRecordBody;
        [SerializeField] private GameObject _waterRecordTemplate;
        public GameObject WaterRecordTemplate => _waterRecordTemplate;
        [SerializeField] private GameObject _waterLoadingState;
        public GameObject WaterLoadingState => _waterLoadingState;
        [SerializeField] private GameObject _waterEmptyState;
        public GameObject WaterEmptyState => _waterEmptyState;
        [SerializeField] private GameObject _waterErrorState;
        public GameObject WaterErrorState => _waterErrorState;
        [SerializeField] private GameObject _waterSuccessState;
        public GameObject WaterSuccessState => _waterSuccessState;
        [SerializeField] private GameObject _waterDisabledState;
        public GameObject WaterDisabledState => _waterDisabledState;
        [SerializeField] private RectTransform _sensorRecordsSamplesContent;
        public RectTransform SensorRecordsSamplesContent => _sensorRecordsSamplesContent;
        [SerializeField] private TMP_Text _sensorRecordsSamplesBody;
        public TMP_Text SensorRecordsSamplesBody => _sensorRecordsSamplesBody;
        [SerializeField] private GameObject _sensorRecordsSamplesTemplate;
        public GameObject SensorRecordsSamplesTemplate => _sensorRecordsSamplesTemplate;
        [SerializeField] private RectTransform _sensorRecordsEventsContent;
        public RectTransform SensorRecordsEventsContent => _sensorRecordsEventsContent;
        [SerializeField] private TMP_Text _sensorRecordsEventsBody;
        public TMP_Text SensorRecordsEventsBody => _sensorRecordsEventsBody;
        [SerializeField] private GameObject _sensorRecordsEventsTemplate;
        public GameObject SensorRecordsEventsTemplate => _sensorRecordsEventsTemplate;
        [SerializeField] private GameObject _sensorRecordsLoadingState;
        public GameObject SensorRecordsLoadingState => _sensorRecordsLoadingState;
        [SerializeField] private GameObject _sensorRecordsEmptyState;
        public GameObject SensorRecordsEmptyState => _sensorRecordsEmptyState;
        [SerializeField] private GameObject _sensorRecordsErrorState;
        public GameObject SensorRecordsErrorState => _sensorRecordsErrorState;
        [SerializeField] private GameObject _sensorRecordsSuccessState;
        public GameObject SensorRecordsSuccessState => _sensorRecordsSuccessState;
        [SerializeField] private GameObject _sensorRecordsDisabledState;
        public GameObject SensorRecordsDisabledState => _sensorRecordsDisabledState;
        [SerializeField] private RectTransform _buildingOverviewIdentityContent;
        public RectTransform BuildingOverviewIdentityContent => _buildingOverviewIdentityContent;
        [SerializeField] private TMP_Text _buildingOverviewIdentityBody;
        public TMP_Text BuildingOverviewIdentityBody => _buildingOverviewIdentityBody;
        [SerializeField] private GameObject _buildingOverviewIdentityTemplate;
        public GameObject BuildingOverviewIdentityTemplate => _buildingOverviewIdentityTemplate;
        [SerializeField] private RectTransform _buildingOverviewOperationContent;
        public RectTransform BuildingOverviewOperationContent => _buildingOverviewOperationContent;
        [SerializeField] private TMP_Text _buildingOverviewOperationBody;
        public TMP_Text BuildingOverviewOperationBody => _buildingOverviewOperationBody;
        [SerializeField] private GameObject _buildingOverviewOperationTemplate;
        public GameObject BuildingOverviewOperationTemplate => _buildingOverviewOperationTemplate;
        [SerializeField] private GameObject _buildingOverviewLoadingState;
        public GameObject BuildingOverviewLoadingState => _buildingOverviewLoadingState;
        [SerializeField] private GameObject _buildingOverviewEmptyState;
        public GameObject BuildingOverviewEmptyState => _buildingOverviewEmptyState;
        [SerializeField] private GameObject _buildingOverviewErrorState;
        public GameObject BuildingOverviewErrorState => _buildingOverviewErrorState;
        [SerializeField] private GameObject _buildingOverviewSuccessState;
        public GameObject BuildingOverviewSuccessState => _buildingOverviewSuccessState;
        [SerializeField] private GameObject _buildingOverviewDisabledState;
        public GameObject BuildingOverviewDisabledState => _buildingOverviewDisabledState;
        [SerializeField] private RectTransform _pumpProductionContent;
        public RectTransform PumpProductionContent => _pumpProductionContent;
        [SerializeField] private TMP_Text _pumpProductionBody;
        public TMP_Text PumpProductionBody => _pumpProductionBody;
        [SerializeField] private GameObject _pumpProductionTemplate;
        public GameObject PumpProductionTemplate => _pumpProductionTemplate;
        [SerializeField] private RectTransform _pumpBlockContent;
        public RectTransform PumpBlockContent => _pumpBlockContent;
        [SerializeField] private TMP_Text _pumpBlockBody;
        public TMP_Text PumpBlockBody => _pumpBlockBody;
        [SerializeField] private GameObject _pumpBlockTemplate;
        public GameObject PumpBlockTemplate => _pumpBlockTemplate;
        [SerializeField] private GameObject _pumpLoadingState;
        public GameObject PumpLoadingState => _pumpLoadingState;
        [SerializeField] private GameObject _pumpEmptyState;
        public GameObject PumpEmptyState => _pumpEmptyState;
        [SerializeField] private GameObject _pumpErrorState;
        public GameObject PumpErrorState => _pumpErrorState;
        [SerializeField] private GameObject _pumpSuccessState;
        public GameObject PumpSuccessState => _pumpSuccessState;
        [SerializeField] private GameObject _pumpDisabledState;
        public GameObject PumpDisabledState => _pumpDisabledState;
        [SerializeField] private RectTransform _generatorPowerContent;
        public RectTransform GeneratorPowerContent => _generatorPowerContent;
        [SerializeField] private TMP_Text _generatorPowerBody;
        public TMP_Text GeneratorPowerBody => _generatorPowerBody;
        [SerializeField] private GameObject _generatorPowerTemplate;
        public GameObject GeneratorPowerTemplate => _generatorPowerTemplate;
        [SerializeField] private RectTransform _generatorChargingContent;
        public RectTransform GeneratorChargingContent => _generatorChargingContent;
        [SerializeField] private TMP_Text _generatorChargingBody;
        public TMP_Text GeneratorChargingBody => _generatorChargingBody;
        [SerializeField] private GameObject _generatorChargingTemplate;
        public GameObject GeneratorChargingTemplate => _generatorChargingTemplate;
        [SerializeField] private GameObject _generatorLoadingState;
        public GameObject GeneratorLoadingState => _generatorLoadingState;
        [SerializeField] private GameObject _generatorEmptyState;
        public GameObject GeneratorEmptyState => _generatorEmptyState;
        [SerializeField] private GameObject _generatorErrorState;
        public GameObject GeneratorErrorState => _generatorErrorState;
        [SerializeField] private GameObject _generatorSuccessState;
        public GameObject GeneratorSuccessState => _generatorSuccessState;
        [SerializeField] private GameObject _generatorDisabledState;
        public GameObject GeneratorDisabledState => _generatorDisabledState;
        [SerializeField] private RectTransform _solarPowerContent;
        public RectTransform SolarPowerContent => _solarPowerContent;
        [SerializeField] private TMP_Text _solarPowerBody;
        public TMP_Text SolarPowerBody => _solarPowerBody;
        [SerializeField] private GameObject _solarPowerTemplate;
        public GameObject SolarPowerTemplate => _solarPowerTemplate;
        [SerializeField] private RectTransform _solarRecoveryContent;
        public RectTransform SolarRecoveryContent => _solarRecoveryContent;
        [SerializeField] private TMP_Text _solarRecoveryBody;
        public TMP_Text SolarRecoveryBody => _solarRecoveryBody;
        [SerializeField] private GameObject _solarRecoveryTemplate;
        public GameObject SolarRecoveryTemplate => _solarRecoveryTemplate;
        [SerializeField] private GameObject _solarLoadingState;
        public GameObject SolarLoadingState => _solarLoadingState;
        [SerializeField] private GameObject _solarEmptyState;
        public GameObject SolarEmptyState => _solarEmptyState;
        [SerializeField] private GameObject _solarErrorState;
        public GameObject SolarErrorState => _solarErrorState;
        [SerializeField] private GameObject _solarSuccessState;
        public GameObject SolarSuccessState => _solarSuccessState;
        [SerializeField] private GameObject _solarDisabledState;
        public GameObject SolarDisabledState => _solarDisabledState;
        [SerializeField] private RectTransform _batteryStorageContent;
        public RectTransform BatteryStorageContent => _batteryStorageContent;
        [SerializeField] private TMP_Text _batteryStorageBody;
        public TMP_Text BatteryStorageBody => _batteryStorageBody;
        [SerializeField] private GameObject _batteryStorageTemplate;
        public GameObject BatteryStorageTemplate => _batteryStorageTemplate;
        [SerializeField] private RectTransform _batteryEstimateContent;
        public RectTransform BatteryEstimateContent => _batteryEstimateContent;
        [SerializeField] private TMP_Text _batteryEstimateBody;
        public TMP_Text BatteryEstimateBody => _batteryEstimateBody;
        [SerializeField] private GameObject _batteryEstimateTemplate;
        public GameObject BatteryEstimateTemplate => _batteryEstimateTemplate;
        [SerializeField] private GameObject _batteryLoadingState;
        public GameObject BatteryLoadingState => _batteryLoadingState;
        [SerializeField] private GameObject _batteryEmptyState;
        public GameObject BatteryEmptyState => _batteryEmptyState;
        [SerializeField] private GameObject _batteryErrorState;
        public GameObject BatteryErrorState => _batteryErrorState;
        [SerializeField] private GameObject _batterySuccessState;
        public GameObject BatterySuccessState => _batterySuccessState;
        [SerializeField] private GameObject _batteryDisabledState;
        public GameObject BatteryDisabledState => _batteryDisabledState;
        [SerializeField] private RectTransform _warehouseBuildingCapacityContent;
        public RectTransform WarehouseBuildingCapacityContent => _warehouseBuildingCapacityContent;
        [SerializeField] private TMP_Text _warehouseBuildingCapacityBody;
        public TMP_Text WarehouseBuildingCapacityBody => _warehouseBuildingCapacityBody;
        [SerializeField] private GameObject _warehouseBuildingCapacityTemplate;
        public GameObject WarehouseBuildingCapacityTemplate => _warehouseBuildingCapacityTemplate;
        [SerializeField] private RectTransform _warehouseBuildingRecentContent;
        public RectTransform WarehouseBuildingRecentContent => _warehouseBuildingRecentContent;
        [SerializeField] private TMP_Text _warehouseBuildingRecentBody;
        public TMP_Text WarehouseBuildingRecentBody => _warehouseBuildingRecentBody;
        [SerializeField] private GameObject _warehouseBuildingRecentTemplate;
        public GameObject WarehouseBuildingRecentTemplate => _warehouseBuildingRecentTemplate;
        [SerializeField] private GameObject _warehouseBuildingLoadingState;
        public GameObject WarehouseBuildingLoadingState => _warehouseBuildingLoadingState;
        [SerializeField] private GameObject _warehouseBuildingEmptyState;
        public GameObject WarehouseBuildingEmptyState => _warehouseBuildingEmptyState;
        [SerializeField] private GameObject _warehouseBuildingErrorState;
        public GameObject WarehouseBuildingErrorState => _warehouseBuildingErrorState;
        [SerializeField] private GameObject _warehouseBuildingSuccessState;
        public GameObject WarehouseBuildingSuccessState => _warehouseBuildingSuccessState;
        [SerializeField] private GameObject _warehouseBuildingDisabledState;
        public GameObject WarehouseBuildingDisabledState => _warehouseBuildingDisabledState;
        [SerializeField] private RectTransform _constructionProgressContent;
        public RectTransform ConstructionProgressContent => _constructionProgressContent;
        [SerializeField] private TMP_Text _constructionProgressBody;
        public TMP_Text ConstructionProgressBody => _constructionProgressBody;
        [SerializeField] private GameObject _constructionProgressTemplate;
        public GameObject ConstructionProgressTemplate => _constructionProgressTemplate;
        [SerializeField] private RectTransform _constructionCostContent;
        public RectTransform ConstructionCostContent => _constructionCostContent;
        [SerializeField] private TMP_Text _constructionCostBody;
        public TMP_Text ConstructionCostBody => _constructionCostBody;
        [SerializeField] private GameObject _constructionCostTemplate;
        public GameObject ConstructionCostTemplate => _constructionCostTemplate;
        [SerializeField] private GameObject _constructionLoadingState;
        public GameObject ConstructionLoadingState => _constructionLoadingState;
        [SerializeField] private GameObject _constructionEmptyState;
        public GameObject ConstructionEmptyState => _constructionEmptyState;
        [SerializeField] private GameObject _constructionErrorState;
        public GameObject ConstructionErrorState => _constructionErrorState;
        [SerializeField] private GameObject _constructionSuccessState;
        public GameObject ConstructionSuccessState => _constructionSuccessState;
        [SerializeField] private GameObject _constructionDisabledState;
        public GameObject ConstructionDisabledState => _constructionDisabledState;
        [SerializeField] private RectTransform _conveyorStateContent;
        public RectTransform ConveyorStateContent => _conveyorStateContent;
        [SerializeField] private TMP_Text _conveyorStateBody;
        public TMP_Text ConveyorStateBody => _conveyorStateBody;
        [SerializeField] private GameObject _conveyorStateTemplate;
        public GameObject ConveyorStateTemplate => _conveyorStateTemplate;
        [SerializeField] private RectTransform _conveyorLinkContent;
        public RectTransform ConveyorLinkContent => _conveyorLinkContent;
        [SerializeField] private TMP_Text _conveyorLinkBody;
        public TMP_Text ConveyorLinkBody => _conveyorLinkBody;
        [SerializeField] private GameObject _conveyorLinkTemplate;
        public GameObject ConveyorLinkTemplate => _conveyorLinkTemplate;
        [SerializeField] private GameObject _conveyorLoadingState;
        public GameObject ConveyorLoadingState => _conveyorLoadingState;
        [SerializeField] private GameObject _conveyorEmptyState;
        public GameObject ConveyorEmptyState => _conveyorEmptyState;
        [SerializeField] private GameObject _conveyorErrorState;
        public GameObject ConveyorErrorState => _conveyorErrorState;
        [SerializeField] private GameObject _conveyorSuccessState;
        public GameObject ConveyorSuccessState => _conveyorSuccessState;
        [SerializeField] private GameObject _conveyorDisabledState;
        public GameObject ConveyorDisabledState => _conveyorDisabledState;
        [SerializeField] private GameObject[] _pageRoots;
        public GameObject[] PageRoots => _pageRoots;
    }
}
