using TMPro;
using UnityEngine;
using UnityEngine.UI;

namespace AutoEra.UI
{
    /// <summary>
    /// OperationDialogForm 的契约绑定字段（由 tools/ui_contract_to_form_script.py 依据
    /// Docs/Development/UI-PrefabLayouts/OperationDialogForm.contract.json 生成，请勿手改）。
    ///
    /// 与 OperationDialogForm.cs 构成同一个 partial 类：字段与只读属性集中在这里，业务逻辑写在
    /// OperationDialogForm.cs。新增节点引用只需改契约再重新生成，不必手写字段。
    /// </summary>
    public sealed partial class OperationDialogForm
    {
        [SerializeField] private RectTransform _pageHost;
        public RectTransform PageHost => _pageHost;
        [SerializeField] private Button _backButton;
        public Button BackButton => _backButton;
        [SerializeField] private Button _closeButton;
        public Button CloseButton => _closeButton;
        [SerializeField] private RectTransform _renameInputContent;
        public RectTransform RenameInputContent => _renameInputContent;
        [SerializeField] private TMP_Text _renameInputBody;
        public TMP_Text RenameInputBody => _renameInputBody;
        [SerializeField] private GameObject _renameInputTemplate;
        public GameObject RenameInputTemplate => _renameInputTemplate;
        [SerializeField] private GameObject _renameLoadingState;
        public GameObject RenameLoadingState => _renameLoadingState;
        [SerializeField] private GameObject _renameEmptyState;
        public GameObject RenameEmptyState => _renameEmptyState;
        [SerializeField] private GameObject _renameErrorState;
        public GameObject RenameErrorState => _renameErrorState;
        [SerializeField] private GameObject _renameSuccessState;
        public GameObject RenameSuccessState => _renameSuccessState;
        [SerializeField] private GameObject _renameDisabledState;
        public GameObject RenameDisabledState => _renameDisabledState;
        [SerializeField] private RectTransform _basicConfirmContextContent;
        public RectTransform BasicConfirmContextContent => _basicConfirmContextContent;
        [SerializeField] private TMP_Text _basicConfirmContextBody;
        public TMP_Text BasicConfirmContextBody => _basicConfirmContextBody;
        [SerializeField] private GameObject _basicConfirmContextTemplate;
        public GameObject BasicConfirmContextTemplate => _basicConfirmContextTemplate;
        [SerializeField] private GameObject _basicConfirmLoadingState;
        public GameObject BasicConfirmLoadingState => _basicConfirmLoadingState;
        [SerializeField] private GameObject _basicConfirmEmptyState;
        public GameObject BasicConfirmEmptyState => _basicConfirmEmptyState;
        [SerializeField] private GameObject _basicConfirmErrorState;
        public GameObject BasicConfirmErrorState => _basicConfirmErrorState;
        [SerializeField] private GameObject _basicConfirmSuccessState;
        public GameObject BasicConfirmSuccessState => _basicConfirmSuccessState;
        [SerializeField] private GameObject _basicConfirmDisabledState;
        public GameObject BasicConfirmDisabledState => _basicConfirmDisabledState;
        [SerializeField] private RectTransform _transactionConfirmItemsContent;
        public RectTransform TransactionConfirmItemsContent => _transactionConfirmItemsContent;
        [SerializeField] private TMP_Text _transactionConfirmItemsBody;
        public TMP_Text TransactionConfirmItemsBody => _transactionConfirmItemsBody;
        [SerializeField] private GameObject _transactionConfirmItemsTemplate;
        public GameObject TransactionConfirmItemsTemplate => _transactionConfirmItemsTemplate;
        [SerializeField] private RectTransform _transactionConfirmQuoteContent;
        public RectTransform TransactionConfirmQuoteContent => _transactionConfirmQuoteContent;
        [SerializeField] private TMP_Text _transactionConfirmQuoteBody;
        public TMP_Text TransactionConfirmQuoteBody => _transactionConfirmQuoteBody;
        [SerializeField] private GameObject _transactionConfirmQuoteTemplate;
        public GameObject TransactionConfirmQuoteTemplate => _transactionConfirmQuoteTemplate;
        [SerializeField] private GameObject _transactionConfirmLoadingState;
        public GameObject TransactionConfirmLoadingState => _transactionConfirmLoadingState;
        [SerializeField] private GameObject _transactionConfirmEmptyState;
        public GameObject TransactionConfirmEmptyState => _transactionConfirmEmptyState;
        [SerializeField] private GameObject _transactionConfirmErrorState;
        public GameObject TransactionConfirmErrorState => _transactionConfirmErrorState;
        [SerializeField] private GameObject _transactionConfirmSuccessState;
        public GameObject TransactionConfirmSuccessState => _transactionConfirmSuccessState;
        [SerializeField] private GameObject _transactionConfirmDisabledState;
        public GameObject TransactionConfirmDisabledState => _transactionConfirmDisabledState;
        [SerializeField] private RectTransform _upgradeConfirmComparisonContent;
        public RectTransform UpgradeConfirmComparisonContent => _upgradeConfirmComparisonContent;
        [SerializeField] private TMP_Text _upgradeConfirmComparisonBody;
        public TMP_Text UpgradeConfirmComparisonBody => _upgradeConfirmComparisonBody;
        [SerializeField] private GameObject _upgradeConfirmComparisonTemplate;
        public GameObject UpgradeConfirmComparisonTemplate => _upgradeConfirmComparisonTemplate;
        [SerializeField] private RectTransform _upgradeConfirmCostsContent;
        public RectTransform UpgradeConfirmCostsContent => _upgradeConfirmCostsContent;
        [SerializeField] private TMP_Text _upgradeConfirmCostsBody;
        public TMP_Text UpgradeConfirmCostsBody => _upgradeConfirmCostsBody;
        [SerializeField] private GameObject _upgradeConfirmCostsTemplate;
        public GameObject UpgradeConfirmCostsTemplate => _upgradeConfirmCostsTemplate;
        [SerializeField] private GameObject _upgradeConfirmLoadingState;
        public GameObject UpgradeConfirmLoadingState => _upgradeConfirmLoadingState;
        [SerializeField] private GameObject _upgradeConfirmEmptyState;
        public GameObject UpgradeConfirmEmptyState => _upgradeConfirmEmptyState;
        [SerializeField] private GameObject _upgradeConfirmErrorState;
        public GameObject UpgradeConfirmErrorState => _upgradeConfirmErrorState;
        [SerializeField] private GameObject _upgradeConfirmSuccessState;
        public GameObject UpgradeConfirmSuccessState => _upgradeConfirmSuccessState;
        [SerializeField] private GameObject _upgradeConfirmDisabledState;
        public GameObject UpgradeConfirmDisabledState => _upgradeConfirmDisabledState;
        [SerializeField] private RectTransform _placementConfirmTargetContent;
        public RectTransform PlacementConfirmTargetContent => _placementConfirmTargetContent;
        [SerializeField] private TMP_Text _placementConfirmTargetBody;
        public TMP_Text PlacementConfirmTargetBody => _placementConfirmTargetBody;
        [SerializeField] private GameObject _placementConfirmTargetTemplate;
        public GameObject PlacementConfirmTargetTemplate => _placementConfirmTargetTemplate;
        [SerializeField] private RectTransform _placementConfirmImpactContent;
        public RectTransform PlacementConfirmImpactContent => _placementConfirmImpactContent;
        [SerializeField] private TMP_Text _placementConfirmImpactBody;
        public TMP_Text PlacementConfirmImpactBody => _placementConfirmImpactBody;
        [SerializeField] private GameObject _placementConfirmImpactTemplate;
        public GameObject PlacementConfirmImpactTemplate => _placementConfirmImpactTemplate;
        [SerializeField] private GameObject _placementConfirmLoadingState;
        public GameObject PlacementConfirmLoadingState => _placementConfirmLoadingState;
        [SerializeField] private GameObject _placementConfirmEmptyState;
        public GameObject PlacementConfirmEmptyState => _placementConfirmEmptyState;
        [SerializeField] private GameObject _placementConfirmErrorState;
        public GameObject PlacementConfirmErrorState => _placementConfirmErrorState;
        [SerializeField] private GameObject _placementConfirmSuccessState;
        public GameObject PlacementConfirmSuccessState => _placementConfirmSuccessState;
        [SerializeField] private GameObject _placementConfirmDisabledState;
        public GameObject PlacementConfirmDisabledState => _placementConfirmDisabledState;
        [SerializeField] private RectTransform _cancelProductionTargetContent;
        public RectTransform CancelProductionTargetContent => _cancelProductionTargetContent;
        [SerializeField] private TMP_Text _cancelProductionTargetBody;
        public TMP_Text CancelProductionTargetBody => _cancelProductionTargetBody;
        [SerializeField] private GameObject _cancelProductionTargetTemplate;
        public GameObject CancelProductionTargetTemplate => _cancelProductionTargetTemplate;
        [SerializeField] private RectTransform _cancelProductionRefundContent;
        public RectTransform CancelProductionRefundContent => _cancelProductionRefundContent;
        [SerializeField] private TMP_Text _cancelProductionRefundBody;
        public TMP_Text CancelProductionRefundBody => _cancelProductionRefundBody;
        [SerializeField] private GameObject _cancelProductionRefundTemplate;
        public GameObject CancelProductionRefundTemplate => _cancelProductionRefundTemplate;
        [SerializeField] private GameObject _cancelProductionLoadingState;
        public GameObject CancelProductionLoadingState => _cancelProductionLoadingState;
        [SerializeField] private GameObject _cancelProductionEmptyState;
        public GameObject CancelProductionEmptyState => _cancelProductionEmptyState;
        [SerializeField] private GameObject _cancelProductionErrorState;
        public GameObject CancelProductionErrorState => _cancelProductionErrorState;
        [SerializeField] private GameObject _cancelProductionSuccessState;
        public GameObject CancelProductionSuccessState => _cancelProductionSuccessState;
        [SerializeField] private GameObject _cancelProductionDisabledState;
        public GameObject CancelProductionDisabledState => _cancelProductionDisabledState;
        [SerializeField] private RectTransform _hardwareConfirmChangeContent;
        public RectTransform HardwareConfirmChangeContent => _hardwareConfirmChangeContent;
        [SerializeField] private TMP_Text _hardwareConfirmChangeBody;
        public TMP_Text HardwareConfirmChangeBody => _hardwareConfirmChangeBody;
        [SerializeField] private GameObject _hardwareConfirmChangeTemplate;
        public GameObject HardwareConfirmChangeTemplate => _hardwareConfirmChangeTemplate;
        [SerializeField] private RectTransform _hardwareConfirmEffectsContent;
        public RectTransform HardwareConfirmEffectsContent => _hardwareConfirmEffectsContent;
        [SerializeField] private TMP_Text _hardwareConfirmEffectsBody;
        public TMP_Text HardwareConfirmEffectsBody => _hardwareConfirmEffectsBody;
        [SerializeField] private GameObject _hardwareConfirmEffectsTemplate;
        public GameObject HardwareConfirmEffectsTemplate => _hardwareConfirmEffectsTemplate;
        [SerializeField] private GameObject _hardwareConfirmLoadingState;
        public GameObject HardwareConfirmLoadingState => _hardwareConfirmLoadingState;
        [SerializeField] private GameObject _hardwareConfirmEmptyState;
        public GameObject HardwareConfirmEmptyState => _hardwareConfirmEmptyState;
        [SerializeField] private GameObject _hardwareConfirmErrorState;
        public GameObject HardwareConfirmErrorState => _hardwareConfirmErrorState;
        [SerializeField] private GameObject _hardwareConfirmSuccessState;
        public GameObject HardwareConfirmSuccessState => _hardwareConfirmSuccessState;
        [SerializeField] private GameObject _hardwareConfirmDisabledState;
        public GameObject HardwareConfirmDisabledState => _hardwareConfirmDisabledState;
        [SerializeField] private RectTransform _machineRecoveryMachineContent;
        public RectTransform MachineRecoveryMachineContent => _machineRecoveryMachineContent;
        [SerializeField] private TMP_Text _machineRecoveryMachineBody;
        public TMP_Text MachineRecoveryMachineBody => _machineRecoveryMachineBody;
        [SerializeField] private GameObject _machineRecoveryMachineTemplate;
        public GameObject MachineRecoveryMachineTemplate => _machineRecoveryMachineTemplate;
        [SerializeField] private RectTransform _machineRecoveryResultContent;
        public RectTransform MachineRecoveryResultContent => _machineRecoveryResultContent;
        [SerializeField] private TMP_Text _machineRecoveryResultBody;
        public TMP_Text MachineRecoveryResultBody => _machineRecoveryResultBody;
        [SerializeField] private GameObject _machineRecoveryResultTemplate;
        public GameObject MachineRecoveryResultTemplate => _machineRecoveryResultTemplate;
        [SerializeField] private GameObject _machineRecoveryLoadingState;
        public GameObject MachineRecoveryLoadingState => _machineRecoveryLoadingState;
        [SerializeField] private GameObject _machineRecoveryEmptyState;
        public GameObject MachineRecoveryEmptyState => _machineRecoveryEmptyState;
        [SerializeField] private GameObject _machineRecoveryErrorState;
        public GameObject MachineRecoveryErrorState => _machineRecoveryErrorState;
        [SerializeField] private GameObject _machineRecoverySuccessState;
        public GameObject MachineRecoverySuccessState => _machineRecoverySuccessState;
        [SerializeField] private GameObject _machineRecoveryDisabledState;
        public GameObject MachineRecoveryDisabledState => _machineRecoveryDisabledState;
        [SerializeField] private RectTransform _algorithmApplyVersionContent;
        public RectTransform AlgorithmApplyVersionContent => _algorithmApplyVersionContent;
        [SerializeField] private TMP_Text _algorithmApplyVersionBody;
        public TMP_Text AlgorithmApplyVersionBody => _algorithmApplyVersionBody;
        [SerializeField] private GameObject _algorithmApplyVersionTemplate;
        public GameObject AlgorithmApplyVersionTemplate => _algorithmApplyVersionTemplate;
        [SerializeField] private RectTransform _algorithmApplyValidationContent;
        public RectTransform AlgorithmApplyValidationContent => _algorithmApplyValidationContent;
        [SerializeField] private TMP_Text _algorithmApplyValidationBody;
        public TMP_Text AlgorithmApplyValidationBody => _algorithmApplyValidationBody;
        [SerializeField] private GameObject _algorithmApplyValidationTemplate;
        public GameObject AlgorithmApplyValidationTemplate => _algorithmApplyValidationTemplate;
        [SerializeField] private GameObject _algorithmApplyLoadingState;
        public GameObject AlgorithmApplyLoadingState => _algorithmApplyLoadingState;
        [SerializeField] private GameObject _algorithmApplyEmptyState;
        public GameObject AlgorithmApplyEmptyState => _algorithmApplyEmptyState;
        [SerializeField] private GameObject _algorithmApplyErrorState;
        public GameObject AlgorithmApplyErrorState => _algorithmApplyErrorState;
        [SerializeField] private GameObject _algorithmApplySuccessState;
        public GameObject AlgorithmApplySuccessState => _algorithmApplySuccessState;
        [SerializeField] private GameObject _algorithmApplyDisabledState;
        public GameObject AlgorithmApplyDisabledState => _algorithmApplyDisabledState;
        [SerializeField] private RectTransform _strongConfirmTargetContent;
        public RectTransform StrongConfirmTargetContent => _strongConfirmTargetContent;
        [SerializeField] private TMP_Text _strongConfirmTargetBody;
        public TMP_Text StrongConfirmTargetBody => _strongConfirmTargetBody;
        [SerializeField] private GameObject _strongConfirmTargetTemplate;
        public GameObject StrongConfirmTargetTemplate => _strongConfirmTargetTemplate;
        [SerializeField] private RectTransform _strongConfirmConsequencesContent;
        public RectTransform StrongConfirmConsequencesContent => _strongConfirmConsequencesContent;
        [SerializeField] private TMP_Text _strongConfirmConsequencesBody;
        public TMP_Text StrongConfirmConsequencesBody => _strongConfirmConsequencesBody;
        [SerializeField] private GameObject _strongConfirmConsequencesTemplate;
        public GameObject StrongConfirmConsequencesTemplate => _strongConfirmConsequencesTemplate;
        [SerializeField] private RectTransform _strongConfirmAcknowledgementContent;
        public RectTransform StrongConfirmAcknowledgementContent => _strongConfirmAcknowledgementContent;
        [SerializeField] private TMP_Text _strongConfirmAcknowledgementBody;
        public TMP_Text StrongConfirmAcknowledgementBody => _strongConfirmAcknowledgementBody;
        [SerializeField] private GameObject _strongConfirmAcknowledgementTemplate;
        public GameObject StrongConfirmAcknowledgementTemplate => _strongConfirmAcknowledgementTemplate;
        [SerializeField] private GameObject _strongConfirmLoadingState;
        public GameObject StrongConfirmLoadingState => _strongConfirmLoadingState;
        [SerializeField] private GameObject _strongConfirmEmptyState;
        public GameObject StrongConfirmEmptyState => _strongConfirmEmptyState;
        [SerializeField] private GameObject _strongConfirmErrorState;
        public GameObject StrongConfirmErrorState => _strongConfirmErrorState;
        [SerializeField] private GameObject _strongConfirmSuccessState;
        public GameObject StrongConfirmSuccessState => _strongConfirmSuccessState;
        [SerializeField] private GameObject _strongConfirmDisabledState;
        public GameObject StrongConfirmDisabledState => _strongConfirmDisabledState;
        [SerializeField] private RectTransform _draftExitDraftContent;
        public RectTransform DraftExitDraftContent => _draftExitDraftContent;
        [SerializeField] private TMP_Text _draftExitDraftBody;
        public TMP_Text DraftExitDraftBody => _draftExitDraftBody;
        [SerializeField] private GameObject _draftExitDraftTemplate;
        public GameObject DraftExitDraftTemplate => _draftExitDraftTemplate;
        [SerializeField] private GameObject _draftExitLoadingState;
        public GameObject DraftExitLoadingState => _draftExitLoadingState;
        [SerializeField] private GameObject _draftExitEmptyState;
        public GameObject DraftExitEmptyState => _draftExitEmptyState;
        [SerializeField] private GameObject _draftExitErrorState;
        public GameObject DraftExitErrorState => _draftExitErrorState;
        [SerializeField] private GameObject _draftExitSuccessState;
        public GameObject DraftExitSuccessState => _draftExitSuccessState;
        [SerializeField] private GameObject _draftExitDisabledState;
        public GameObject DraftExitDisabledState => _draftExitDisabledState;
        [SerializeField] private RectTransform _forceExitLossContent;
        public RectTransform ForceExitLossContent => _forceExitLossContent;
        [SerializeField] private TMP_Text _forceExitLossBody;
        public TMP_Text ForceExitLossBody => _forceExitLossBody;
        [SerializeField] private GameObject _forceExitLossTemplate;
        public GameObject ForceExitLossTemplate => _forceExitLossTemplate;
        [SerializeField] private GameObject _forceExitLoadingState;
        public GameObject ForceExitLoadingState => _forceExitLoadingState;
        [SerializeField] private GameObject _forceExitEmptyState;
        public GameObject ForceExitEmptyState => _forceExitEmptyState;
        [SerializeField] private GameObject _forceExitErrorState;
        public GameObject ForceExitErrorState => _forceExitErrorState;
        [SerializeField] private GameObject _forceExitSuccessState;
        public GameObject ForceExitSuccessState => _forceExitSuccessState;
        [SerializeField] private GameObject _forceExitDisabledState;
        public GameObject ForceExitDisabledState => _forceExitDisabledState;
        [SerializeField] private RectTransform _displayKeepModesContent;
        public RectTransform DisplayKeepModesContent => _displayKeepModesContent;
        [SerializeField] private TMP_Text _displayKeepModesBody;
        public TMP_Text DisplayKeepModesBody => _displayKeepModesBody;
        [SerializeField] private GameObject _displayKeepModesTemplate;
        public GameObject DisplayKeepModesTemplate => _displayKeepModesTemplate;
        [SerializeField] private RectTransform _displayKeepRecoveryContent;
        public RectTransform DisplayKeepRecoveryContent => _displayKeepRecoveryContent;
        [SerializeField] private TMP_Text _displayKeepRecoveryBody;
        public TMP_Text DisplayKeepRecoveryBody => _displayKeepRecoveryBody;
        [SerializeField] private GameObject _displayKeepRecoveryTemplate;
        public GameObject DisplayKeepRecoveryTemplate => _displayKeepRecoveryTemplate;
        [SerializeField] private GameObject _displayKeepLoadingState;
        public GameObject DisplayKeepLoadingState => _displayKeepLoadingState;
        [SerializeField] private GameObject _displayKeepEmptyState;
        public GameObject DisplayKeepEmptyState => _displayKeepEmptyState;
        [SerializeField] private GameObject _displayKeepErrorState;
        public GameObject DisplayKeepErrorState => _displayKeepErrorState;
        [SerializeField] private GameObject _displayKeepSuccessState;
        public GameObject DisplayKeepSuccessState => _displayKeepSuccessState;
        [SerializeField] private GameObject _displayKeepDisabledState;
        public GameObject DisplayKeepDisabledState => _displayKeepDisabledState;
        [SerializeField] private GameObject[] _pageRoots;
        public GameObject[] PageRoots => _pageRoots;
    }
}
