using TMPro;
using UnityEngine;
using UnityEngine.UI;

namespace AutoEra.UI
{
    /// <summary>
    /// ProgressReportForm 的契约绑定字段（由 tools/ui_contract_to_form_script.py 依据
    /// Docs/Development/UI-PrefabLayouts/ProgressReportForm.contract.json 生成，请勿手改）。
    ///
    /// 与 ProgressReportForm.cs 构成同一个 partial 类：字段与只读属性集中在这里，业务逻辑写在
    /// ProgressReportForm.cs。新增节点引用只需改契约再重新生成，不必手写字段。
    /// </summary>
    public sealed partial class ProgressReportForm
    {
        [SerializeField] private RectTransform _pageHost;
        public RectTransform PageHost => _pageHost;
        [SerializeField] private Button _backButton;
        public Button BackButton => _backButton;
        [SerializeField] private Button _closeButton;
        public Button CloseButton => _closeButton;
        [SerializeField] private RectTransform _loadingStageContent;
        public RectTransform LoadingStageContent => _loadingStageContent;
        [SerializeField] private TMP_Text _loadingStageBody;
        public TMP_Text LoadingStageBody => _loadingStageBody;
        [SerializeField] private GameObject _loadingStageTemplate;
        public GameObject LoadingStageTemplate => _loadingStageTemplate;
        [SerializeField] private RectTransform _loadingFailureContent;
        public RectTransform LoadingFailureContent => _loadingFailureContent;
        [SerializeField] private TMP_Text _loadingFailureBody;
        public TMP_Text LoadingFailureBody => _loadingFailureBody;
        [SerializeField] private GameObject _loadingFailureTemplate;
        public GameObject LoadingFailureTemplate => _loadingFailureTemplate;
        [SerializeField] private GameObject _loadingLoadingState;
        public GameObject LoadingLoadingState => _loadingLoadingState;
        [SerializeField] private GameObject _loadingEmptyState;
        public GameObject LoadingEmptyState => _loadingEmptyState;
        [SerializeField] private GameObject _loadingErrorState;
        public GameObject LoadingErrorState => _loadingErrorState;
        [SerializeField] private GameObject _loadingSuccessState;
        public GameObject LoadingSuccessState => _loadingSuccessState;
        [SerializeField] private GameObject _loadingDisabledState;
        public GameObject LoadingDisabledState => _loadingDisabledState;
        [SerializeField] private RectTransform _offlineSettlementStageContent;
        public RectTransform OfflineSettlementStageContent => _offlineSettlementStageContent;
        [SerializeField] private TMP_Text _offlineSettlementStageBody;
        public TMP_Text OfflineSettlementStageBody => _offlineSettlementStageBody;
        [SerializeField] private GameObject _offlineSettlementStageTemplate;
        public GameObject OfflineSettlementStageTemplate => _offlineSettlementStageTemplate;
        [SerializeField] private RectTransform _offlineSettlementResumeContent;
        public RectTransform OfflineSettlementResumeContent => _offlineSettlementResumeContent;
        [SerializeField] private TMP_Text _offlineSettlementResumeBody;
        public TMP_Text OfflineSettlementResumeBody => _offlineSettlementResumeBody;
        [SerializeField] private GameObject _offlineSettlementResumeTemplate;
        public GameObject OfflineSettlementResumeTemplate => _offlineSettlementResumeTemplate;
        [SerializeField] private GameObject _offlineSettlementLoadingState;
        public GameObject OfflineSettlementLoadingState => _offlineSettlementLoadingState;
        [SerializeField] private GameObject _offlineSettlementEmptyState;
        public GameObject OfflineSettlementEmptyState => _offlineSettlementEmptyState;
        [SerializeField] private GameObject _offlineSettlementErrorState;
        public GameObject OfflineSettlementErrorState => _offlineSettlementErrorState;
        [SerializeField] private GameObject _offlineSettlementSuccessState;
        public GameObject OfflineSettlementSuccessState => _offlineSettlementSuccessState;
        [SerializeField] private GameObject _offlineSettlementDisabledState;
        public GameObject OfflineSettlementDisabledState => _offlineSettlementDisabledState;
        [SerializeField] private RectTransform _returnReportSectionsContent;
        public RectTransform ReturnReportSectionsContent => _returnReportSectionsContent;
        [SerializeField] private TMP_Text _returnReportSectionsBody;
        public TMP_Text ReturnReportSectionsBody => _returnReportSectionsBody;
        [SerializeField] private GameObject _returnReportSectionsTemplate;
        public GameObject ReturnReportSectionsTemplate => _returnReportSectionsTemplate;
        [SerializeField] private RectTransform _returnReportDetailsContent;
        public RectTransform ReturnReportDetailsContent => _returnReportDetailsContent;
        [SerializeField] private TMP_Text _returnReportDetailsBody;
        public TMP_Text ReturnReportDetailsBody => _returnReportDetailsBody;
        [SerializeField] private GameObject _returnReportDetailsTemplate;
        public GameObject ReturnReportDetailsTemplate => _returnReportDetailsTemplate;
        [SerializeField] private GameObject _returnReportLoadingState;
        public GameObject ReturnReportLoadingState => _returnReportLoadingState;
        [SerializeField] private GameObject _returnReportEmptyState;
        public GameObject ReturnReportEmptyState => _returnReportEmptyState;
        [SerializeField] private GameObject _returnReportErrorState;
        public GameObject ReturnReportErrorState => _returnReportErrorState;
        [SerializeField] private GameObject _returnReportSuccessState;
        public GameObject ReturnReportSuccessState => _returnReportSuccessState;
        [SerializeField] private GameObject _returnReportDisabledState;
        public GameObject ReturnReportDisabledState => _returnReportDisabledState;
        [SerializeField] private RectTransform _backupProgressRecoveryContent;
        public RectTransform BackupProgressRecoveryContent => _backupProgressRecoveryContent;
        [SerializeField] private TMP_Text _backupProgressRecoveryBody;
        public TMP_Text BackupProgressRecoveryBody => _backupProgressRecoveryBody;
        [SerializeField] private GameObject _backupProgressRecoveryTemplate;
        public GameObject BackupProgressRecoveryTemplate => _backupProgressRecoveryTemplate;
        [SerializeField] private RectTransform _backupProgressOutcomeContent;
        public RectTransform BackupProgressOutcomeContent => _backupProgressOutcomeContent;
        [SerializeField] private TMP_Text _backupProgressOutcomeBody;
        public TMP_Text BackupProgressOutcomeBody => _backupProgressOutcomeBody;
        [SerializeField] private GameObject _backupProgressOutcomeTemplate;
        public GameObject BackupProgressOutcomeTemplate => _backupProgressOutcomeTemplate;
        [SerializeField] private GameObject _backupProgressLoadingState;
        public GameObject BackupProgressLoadingState => _backupProgressLoadingState;
        [SerializeField] private GameObject _backupProgressEmptyState;
        public GameObject BackupProgressEmptyState => _backupProgressEmptyState;
        [SerializeField] private GameObject _backupProgressErrorState;
        public GameObject BackupProgressErrorState => _backupProgressErrorState;
        [SerializeField] private GameObject _backupProgressSuccessState;
        public GameObject BackupProgressSuccessState => _backupProgressSuccessState;
        [SerializeField] private GameObject _backupProgressDisabledState;
        public GameObject BackupProgressDisabledState => _backupProgressDisabledState;
        [SerializeField] private RectTransform _deliverySummaryContent;
        public RectTransform DeliverySummaryContent => _deliverySummaryContent;
        [SerializeField] private TMP_Text _deliverySummaryBody;
        public TMP_Text DeliverySummaryBody => _deliverySummaryBody;
        [SerializeField] private GameObject _deliverySummaryTemplate;
        public GameObject DeliverySummaryTemplate => _deliverySummaryTemplate;
        [SerializeField] private RectTransform _deliveryDestinationsContent;
        public RectTransform DeliveryDestinationsContent => _deliveryDestinationsContent;
        [SerializeField] private TMP_Text _deliveryDestinationsBody;
        public TMP_Text DeliveryDestinationsBody => _deliveryDestinationsBody;
        [SerializeField] private GameObject _deliveryDestinationsTemplate;
        public GameObject DeliveryDestinationsTemplate => _deliveryDestinationsTemplate;
        [SerializeField] private GameObject _deliveryLoadingState;
        public GameObject DeliveryLoadingState => _deliveryLoadingState;
        [SerializeField] private GameObject _deliveryEmptyState;
        public GameObject DeliveryEmptyState => _deliveryEmptyState;
        [SerializeField] private GameObject _deliveryErrorState;
        public GameObject DeliveryErrorState => _deliveryErrorState;
        [SerializeField] private GameObject _deliverySuccessState;
        public GameObject DeliverySuccessState => _deliverySuccessState;
        [SerializeField] private GameObject _deliveryDisabledState;
        public GameObject DeliveryDisabledState => _deliveryDisabledState;
        [SerializeField] private RectTransform _growthLevelContent;
        public RectTransform GrowthLevelContent => _growthLevelContent;
        [SerializeField] private TMP_Text _growthLevelBody;
        public TMP_Text GrowthLevelBody => _growthLevelBody;
        [SerializeField] private GameObject _growthLevelTemplate;
        public GameObject GrowthLevelTemplate => _growthLevelTemplate;
        [SerializeField] private RectTransform _growthUnlocksContent;
        public RectTransform GrowthUnlocksContent => _growthUnlocksContent;
        [SerializeField] private TMP_Text _growthUnlocksBody;
        public TMP_Text GrowthUnlocksBody => _growthUnlocksBody;
        [SerializeField] private GameObject _growthUnlocksTemplate;
        public GameObject GrowthUnlocksTemplate => _growthUnlocksTemplate;
        [SerializeField] private GameObject _growthLoadingState;
        public GameObject GrowthLoadingState => _growthLoadingState;
        [SerializeField] private GameObject _growthEmptyState;
        public GameObject GrowthEmptyState => _growthEmptyState;
        [SerializeField] private GameObject _growthErrorState;
        public GameObject GrowthErrorState => _growthErrorState;
        [SerializeField] private GameObject _growthSuccessState;
        public GameObject GrowthSuccessState => _growthSuccessState;
        [SerializeField] private GameObject _growthDisabledState;
        public GameObject GrowthDisabledState => _growthDisabledState;
        [SerializeField] private RectTransform _dailySupplyOfferContent;
        public RectTransform DailySupplyOfferContent => _dailySupplyOfferContent;
        [SerializeField] private TMP_Text _dailySupplyOfferBody;
        public TMP_Text DailySupplyOfferBody => _dailySupplyOfferBody;
        [SerializeField] private GameObject _dailySupplyOfferTemplate;
        public GameObject DailySupplyOfferTemplate => _dailySupplyOfferTemplate;
        [SerializeField] private RectTransform _dailySupplyRulesContent;
        public RectTransform DailySupplyRulesContent => _dailySupplyRulesContent;
        [SerializeField] private TMP_Text _dailySupplyRulesBody;
        public TMP_Text DailySupplyRulesBody => _dailySupplyRulesBody;
        [SerializeField] private GameObject _dailySupplyRulesTemplate;
        public GameObject DailySupplyRulesTemplate => _dailySupplyRulesTemplate;
        [SerializeField] private GameObject _dailySupplyLoadingState;
        public GameObject DailySupplyLoadingState => _dailySupplyLoadingState;
        [SerializeField] private GameObject _dailySupplyEmptyState;
        public GameObject DailySupplyEmptyState => _dailySupplyEmptyState;
        [SerializeField] private GameObject _dailySupplyErrorState;
        public GameObject DailySupplyErrorState => _dailySupplyErrorState;
        [SerializeField] private GameObject _dailySupplySuccessState;
        public GameObject DailySupplySuccessState => _dailySupplySuccessState;
        [SerializeField] private GameObject _dailySupplyDisabledState;
        public GameObject DailySupplyDisabledState => _dailySupplyDisabledState;
        [SerializeField] private RectTransform _versionCompleteAchievementContent;
        public RectTransform VersionCompleteAchievementContent => _versionCompleteAchievementContent;
        [SerializeField] private TMP_Text _versionCompleteAchievementBody;
        public TMP_Text VersionCompleteAchievementBody => _versionCompleteAchievementBody;
        [SerializeField] private GameObject _versionCompleteAchievementTemplate;
        public GameObject VersionCompleteAchievementTemplate => _versionCompleteAchievementTemplate;
        [SerializeField] private RectTransform _versionCompleteBoundaryContent;
        public RectTransform VersionCompleteBoundaryContent => _versionCompleteBoundaryContent;
        [SerializeField] private TMP_Text _versionCompleteBoundaryBody;
        public TMP_Text VersionCompleteBoundaryBody => _versionCompleteBoundaryBody;
        [SerializeField] private GameObject _versionCompleteBoundaryTemplate;
        public GameObject VersionCompleteBoundaryTemplate => _versionCompleteBoundaryTemplate;
        [SerializeField] private GameObject _versionCompleteLoadingState;
        public GameObject VersionCompleteLoadingState => _versionCompleteLoadingState;
        [SerializeField] private GameObject _versionCompleteEmptyState;
        public GameObject VersionCompleteEmptyState => _versionCompleteEmptyState;
        [SerializeField] private GameObject _versionCompleteErrorState;
        public GameObject VersionCompleteErrorState => _versionCompleteErrorState;
        [SerializeField] private GameObject _versionCompleteSuccessState;
        public GameObject VersionCompleteSuccessState => _versionCompleteSuccessState;
        [SerializeField] private GameObject _versionCompleteDisabledState;
        public GameObject VersionCompleteDisabledState => _versionCompleteDisabledState;
        [SerializeField] private GameObject[] _pageRoots;
        public GameObject[] PageRoots => _pageRoots;
    }
}
