#!/usr/bin/env python3
"""sync-agents.py

将 .claude/agents/*.md（source of truth）同步到 .codex/agents/*.toml。

用法：
    python tools/sync-agents.py            # 同步
    python tools/sync-agents.py --check    # 仅校验差异，不写入（CI 用）
    python tools/sync-agents.py --verbose  # 输出每个文件的同步细节

约定：
- .claude/agents/<name>.md 的 frontmatter 与 body 是 source of truth
- .codex/agents/<name>.toml 使用原生 developer_instructions；默认继承宿主模型
- 多余 agent 只报告，不自动删除；来源删除后的清理由用户明确授权
- .claude/skills/ 是唯一 skill 源；.agents/skills 为本机发现链接，不复制正文
"""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
import tomllib
from pathlib import Path

try:
    import yaml  # PyYAML
except ImportError:
    print("ERROR: 需要 PyYAML。请运行: pip install pyyaml")
    sys.exit(2)


ROOT = Path(__file__).resolve().parent.parent
CLAUDE_AGENTS = ROOT / ".claude" / "agents"
CODEX_AGENTS = ROOT / ".codex" / "agents"


def parse_md(path: Path) -> tuple[dict, str]:
    """从 .md 中提取 frontmatter dict 与 body 字符串。"""
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---"):
        raise ValueError(f"{path} 缺少 frontmatter")
    parts = text.split("---", 2)
    if len(parts) < 3:
        raise ValueError(f"{path} frontmatter 格式不正确")
    fm = yaml.safe_load(parts[1]) or {}
    body = parts[2].lstrip("\n")
    return fm, body


def to_toml(fm: dict, body: str) -> str:
    """Claude 模型/工具字段不作为 Codex 配置；技能仅提供推荐。"""
    quote = lambda value: json.dumps(value, ensure_ascii=False)
    skills = fm.get("skills", []) or []
    if isinstance(skills, str):
        skills = [s.strip() for s in skills.split(",")]
    note = "推荐技能（非权限白名单）：" + ", ".join(skills)
    instructions = body.rstrip() + "\n\n" + note + "\n可按任务使用其他可用技能；不扩大授权、写范围或工具占用。\n"
    lines = ["# Generated by tools/sync-agents.py; do not edit.",
             f'name = {quote(fm["name"])}',
             f'description = {quote(fm["description"])}',
             f'developer_instructions = {quote(instructions)}']
    content = "\n".join(lines) + "\n"
    parsed = tomllib.loads(content)
    assert parsed["developer_instructions"] == instructions
    return content


def sync_skills(check: bool) -> int:
    """建立标准发现链接；拒绝覆盖已有非目标目录或失效链接。"""
    source = ROOT / ".claude" / "skills"
    link = ROOT / ".agents" / "skills"
    if os.path.lexists(link):
        if link.resolve() == source.resolve():
            return 0
        print("ERROR: .agents/skills 已存在但不是技能源链接；未覆盖")
        return 2
    if check:
        print("DIFF: 缺少 .agents/skills 发现链接，请运行同步")
        return 1
    link.parent.mkdir(parents=True, exist_ok=True)
    if os.name == "nt":
        escape = lambda p: str(p).replace("'", "''")
        subprocess.run(["powershell", "-NoProfile", "-NonInteractive", "-Command",
                        f"New-Item -ItemType Junction -Path '{escape(link)}' -Target '{escape(source)}' -ErrorAction Stop | Out-Null"], check=True)
    else:
        link.symlink_to(Path("..") / ".claude" / "skills", target_is_directory=True)
    return 0


def sync_agents(check: bool, verbose: bool) -> int:
    """返回 0 = 同步通过 / 1 = 存在差异（check 模式下）"""
    if not CLAUDE_AGENTS.exists():
        print(f"ERROR: 源不存在 {CLAUDE_AGENTS}")
        return 2
    if not check:
        CODEX_AGENTS.mkdir(parents=True, exist_ok=True)

    diff_count = 0
    source_names = set()

    for md_path in sorted(CLAUDE_AGENTS.glob("*.md")):
        name = md_path.stem
        source_names.add(name)
        try:
            fm, body = parse_md(md_path)
        except Exception as e:
            print(f"ERROR: 解析 {md_path} 失败: {e}")
            return 2

        toml_path = CODEX_AGENTS / f"{name}.toml"
        new_content = to_toml(fm, body)
        old_content = toml_path.read_text(encoding="utf-8") if toml_path.exists() else ""

        if new_content != old_content:
            diff_count += 1
            if check:
                if verbose:
                    print(f"DIFF: {toml_path.relative_to(ROOT)}")
            else:
                toml_path.write_text(new_content, encoding="utf-8")
                if verbose:
                    print(f"WROTE: {toml_path.relative_to(ROOT)}")
        elif verbose:
            print(f"OK:    {toml_path.relative_to(ROOT)}")

    # 清理 .codex/agents/ 中 .claude/agents/ 已不存在的项
    for toml_path in sorted(CODEX_AGENTS.glob("*.toml")):
        if toml_path.stem not in source_names:
            diff_count += 1
            if check:
                if verbose:
                    print(f"EXTRA: {toml_path.relative_to(ROOT)}（源已删，应同步删除）")
            else:
                print(f"ERROR: 保留无来源文件 {toml_path.relative_to(ROOT)}，需确认归属")
                return 2

    return 1 if (check and diff_count > 0) else 0


def main() -> int:
    p = argparse.ArgumentParser(description="同步 .claude/agents/ → .codex/agents/")
    p.add_argument("--check", action="store_true", help="仅校验，不写入；存在差异时退出码非 0")
    p.add_argument("--verbose", "-v", action="store_true", help="输出每个文件的处理结果")
    p.add_argument("--skip-skills", action="store_true", help="仅处理角色配置，不建立或检查技能发现链接")
    args = p.parse_args()

    rc1 = sync_agents(args.check, args.verbose)
    rc2 = 0 if args.skip_skills else sync_skills(args.check)

    if args.check:
        if rc1 or rc2:
            print("[FAIL] 存在差异。请运行 `python tools/sync-agents.py` 同步后重新提交。")
            return 1
        print("[OK] agents 与技能发现入口一致。")
    else:
        print(f"sync 完成（agents rc={rc1}, skills rc={rc2}）")
    return max(rc1, rc2)


if __name__ == "__main__":
    sys.exit(main())
